namespace Coplt.Mathematics.Algebras;

#region Core

public interface IMatrix<TSelf> : IAlgebra<TSelf>
    where TSelf : unmanaged, IMatrix<TSelf>
{
    #region Meta

    public static abstract int Rows { get; }
    public static abstract int Columns { get; }
    public static abstract int Length { get; }

    #endregion

    #region Constants

    public static abstract TSelf Identity { get; }

    #endregion
}

public interface IMatrixVector<TSelf, TVector> :
    IMatrix<TSelf>
    where TSelf : unmanaged, IMatrixVector<TSelf, TVector>
    where TVector : unmanaged, IVector<TVector>
{
    #region Constants

    public static abstract TVector VectorZero { get; }
    public static abstract TVector VectorOne { get; }
    public static abstract TVector VectorTwo { get; }

    #endregion

    #region Ctor

    public static abstract TSelf Broadcast(in TVector scalar);
    public static abstract TSelf Vector(in TVector scalar);
    public static abstract TSelf Load(ReadOnlySpan<TVector> span);
    public static abstract unsafe TSelf Load(TVector* ptr);

    #endregion

    #region Index

    public static abstract TVector get_vector(in TSelf self, int index);
    public static abstract void set_vector(ref TSelf self, int index, in TVector value);

    #endregion
}

public interface IMatrixScalar<TSelf, TScalar> :
    IMatrix<TSelf>, IAlgebra<TSelf, TScalar>
    where TSelf : unmanaged, IMatrixScalar<TSelf, TScalar>
    where TScalar : unmanaged
{
    #region Index

    public static abstract TScalar get(in TSelf self, int row, int column);
    public static abstract void set(ref TSelf self, int row, int column, TScalar value);

    #endregion
}

#endregion

#region Bool

public interface IBoolMatrix<TSelf> : IMatrix<TSelf>, IBoolAlgebra<TSelf>
    where TSelf : unmanaged, IBoolMatrix<TSelf>;

public interface IBoolMatrix<TSelf, TScalar> : IMatrixScalar<TSelf, TScalar>, IBoolAlgebra<TSelf, TScalar>
    where TSelf : unmanaged, IBoolMatrix<TSelf, TScalar>
    where TScalar : unmanaged;

#endregion

#region Number

public interface INumberMatrix<TSelf> : IMatrix<TSelf>, INumberAlgebra<TSelf>
    where TSelf : unmanaged, INumberMatrix<TSelf>;

public interface INumberMatrix<TSelf, TScalar> : IMatrixScalar<TSelf, TScalar>, INumberAlgebra<TSelf, TScalar>
    where TSelf : unmanaged, INumberMatrix<TSelf, TScalar>
    where TScalar : unmanaged, INumberBase<TScalar>;

#endregion

#region Signed

public interface ISignedNumberMatrix<TSelf> : INumberMatrix<TSelf>
    where TSelf : unmanaged, ISignedNumberMatrix<TSelf>;

public interface ISignedNumberMatrix<TSelf, TScalar> : INumberMatrix<TSelf, TScalar>
    where TSelf : unmanaged, ISignedNumberMatrix<TSelf, TScalar>
    where TScalar : unmanaged, INumberBase<TScalar>;

#endregion

// The interfaces of the shapes of a matrix are generated by Coplt.Analyzers.Generators.MatrixShapeGenerator.
// Every shape of 2 rows to 4 rows and 2 columns to 4 columns has the interface of its own, the form that
// reaches the columns of the matrix through a vector and the form that reaches the components of it by a
// scalar.
