using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Coplt.Analyzers.Generators;

/// <summary>
/// Generates the members of the scalar types of a vector that forward to a member of the <c>math</c> class that
/// is marked with <see cref="Attribute"/>. The type of a single component of the value a member returns is only
/// a part of its result, so the compiler cannot infer it from the arguments and a call that does not name it
/// reaches the member of the scalar type of the vector it is called on, which names the type itself and forwards
/// the call to the marked member.
/// <para>The members of a scalar type are emitted into two classes: <c>ex_*</c> adds them to the <c>math</c>
/// class, so the type of a single component is named where the member is called and the other types of it are
/// still inferred, and <c>math_ex_*</c> adds them to the value itself, so the call reads like the member of the
/// vector. A member of a class cannot be overloaded on its constraints alone, so every scalar type has a class of
/// its own. The marked member names the type of a single component with a type parameter of its own, which is
/// <c>TScalar</c> unless the attribute says otherwise, and the generated member is the one of the marked member
/// with that type spelled out and its body is the forwarding of the call.</para>
/// </summary>
[Generator]
public class ScalarExtensionGenerator : IIncrementalGenerator
{
    /// <summary>The namespace of the generated members, which is the one of the <c>math</c> class.</summary>
    public const string Namespace = "Coplt.Mathematics";

    /// <summary>The name of the attribute a member is marked with.</summary>
    public const string Attribute = "ScalarExtensionAttribute";

    /// <summary>The name of the type parameter of a marked member that names the type of a single component.</summary>
    public const string DefaultScalarTypeParameter = "TScalar";

    /// <summary>The attribute of a member, it is inlined into its caller.</summary>
    private const string Attr = "[MethodImpl(MethodImplOptions.AggressiveInlining)]";

    /// <summary>
    /// The format of the name of a type in a generated member: the namespace and the containing types of a type
    /// are spelled out, so a member names the type of the marked member itself instead of the one a name reaches
    /// through the usings of the generated file, and a type of the language is named by the keyword of it.
    /// </summary>
    private static readonly SymbolDisplayFormat TypeFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted)
        .WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions | SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx => ctx.AddSource(
            $"{Namespace}.{Attribute}.g.cs",
            SourceText.From(GenAttribute(), Encoding.UTF8)));

        var members = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                $"{Namespace}.{Attribute}",
                static (node, _) => node is MethodDeclarationSyntax,
                static (ctx, _) => ctx.TargetSymbol as IMethodSymbol)
            .Where(static member => member is not null);

        context.RegisterSourceOutput(members, static (ctx, member) => Emit(ctx, member!));
    }

    /// <summary>
    /// Generates the attribute a member of the <c>math</c> class is marked with.
    /// </summary>
    /// <returns>The file of the attribute</returns>
    private static string GenAttribute()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Marks a member of the <c>math</c> class that names the type of a single component of the value it");
        sb.AppendLine("/// returns with a type parameter of its own. The generator emits the member of every scalar type of a");
        sb.AppendLine("/// vector that names the type itself and forwards the call to the marked member, so a call that does not");
        sb.AppendLine("/// name the type of a single component reaches the member of the scalar type of the vector it is called on.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[global::System.AttributeUsage(global::System.AttributeTargets.Method)]");
        sb.AppendLine($"public sealed class {Attribute} : global::System.Attribute");
        sb.AppendLine("{");
        sb.AppendLine("    /// <param name=\"scalarTypeParameter\">The name of the type parameter of the marked member that names the type of a single component</param>");
        sb.AppendLine($"    public {Attribute}(string scalarTypeParameter = \"{DefaultScalarTypeParameter}\") => ScalarTypeParameter = scalarTypeParameter;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>The name of the type parameter of the marked member that names the type of a single component</summary>");
        sb.AppendLine("    public string ScalarTypeParameter { get; }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Emits the members of every scalar type of a vector for a marked member.
    /// </summary>
    /// <param name="context">The context of the generation</param>
    /// <param name="method">The marked member</param>
    private static void Emit(SourceProductionContext context, IMethodSymbol method)
    {
        var scalarTypeParameter = ScalarTypeParameter(method);
        // the member is marked for the type of a single component, so it has to name it with a type parameter of
        // its own
        var component = method.TypeParameters.FirstOrDefault(p => p.Name == scalarTypeParameter);
        if (component is null) return;

        // the type of a single component is spelled out by the generated member, the rest of the type parameters
        // are kept and inferred as they are
        var typeParameters = method.TypeParameters.Where(p => !SymbolEqualityComparer.Default.Equals(p, component)).ToArray();

        foreach (var typ in Typ.Typs)
        {
            // only a number type has arithmetic, a bool vector has no dot product at all
            if (!typ.arith || typ.bol) continue;
            context.AddSource(
                $"{Namespace}.{method.Name}.{typ.name}.g.cs",
                SourceText.From(Gen(typ.name, method, scalarTypeParameter, typeParameters), Encoding.UTF8));
        }
    }

    /// <summary>
    /// Returns the name of the type parameter of a marked member that names the type of a single component, which
    /// is the one the attribute names.
    /// </summary>
    /// <param name="method">The marked member</param>
    /// <returns>The name of the type parameter</returns>
    private static string ScalarTypeParameter(IMethodSymbol method)
    {
        foreach (var attribute in method.GetAttributes())
        {
            if (attribute.AttributeClass?.Name != Attribute) continue;
            if (attribute.ConstructorArguments.Length == 0) continue;
            if (attribute.ConstructorArguments[0].Value is string name && name.Length != 0) return name;
        }
        return DefaultScalarTypeParameter;
    }

    /// <summary>
    /// Returns the reference to the marked member, which is what a generated member inherits its documentation
    /// from: the name of the member, the type parameters of it and the types of its parameters.
    /// </summary>
    /// <param name="method">The marked member</param>
    /// <returns>The reference</returns>
    private static string Cref(IMethodSymbol method)
    {
        var typeParameters = method.TypeParameters.Length == 0
            ? ""
            : $"{{{string.Join(", ", method.TypeParameters.Select(p => p.Name))}}}";
        var parameters = string.Join(", ", method.Parameters.Select(p => $"{RefKindText(p.RefKind)}{p.Type.ToDisplayString(TypeFormat)}"));
        return $"{method.ContainingType.Name}.{method.Name}{typeParameters}({parameters})";
    }

    /// <summary>
    /// Returns the keyword a parameter of a member is declared with.
    /// </summary>
    /// <param name="kind">The kind of the parameter</param>
    /// <returns>The keyword, which is empty for a parameter that is passed by value</returns>
    private static string RefKindText(RefKind kind) => kind switch
    {
        RefKind.In => "in ",
        RefKind.Ref => "ref ",
        RefKind.Out => "out ",
        RefKind.RefReadOnlyParameter => "ref readonly ",
        _ => ""
    };

    /// <summary>
    /// Generates the members of the scalar type <paramref name="scalar"/> that forward to <paramref name="method"/>.
    /// </summary>
    /// <param name="scalar">The scalar type of a single component</param>
    /// <param name="method">The marked member</param>
    /// <param name="scalarTypeParameter">The name of the type parameter of the marked member that names the type of a single component</param>
    /// <param name="typeParameters">The type parameters of the marked member beside the one of a single component</param>
    /// <returns>The file of the members</returns>
    private static string Gen(string scalar, IMethodSymbol method, string scalarTypeParameter, ITypeParameterSymbol[] typeParameters)
    {
        // the marked member names the type of a single component, a generated member names the type itself, so
        // every type that carries the type parameter of it is written with the scalar type
        string Type(ITypeSymbol type) => type.ToDisplayString(TypeFormat).Replace(scalarTypeParameter, scalar);

        // every type parameter of the marked member beside the one of a single component is inferred from the
        // arguments, the one of a single component is named by the generated member
        var typeArguments = string.Join(", ", method.TypeParameters.Select(p => p.Name == scalarTypeParameter ? scalar : p.Name));
        var typeParametersText = typeParameters.Length == 0 ? "" : $"<{string.Join(", ", typeParameters.Select(p => p.Name))}>";

        // the parameters of a member of the math class are the ones of the marked member
        var parameters = string.Join(", ", method.Parameters.Select(p => $"{RefKindText(p.RefKind)}{Type(p.Type)} {p.Name}"));

        // the receiver of a member of the value is the first parameter of the marked member, it is passed by
        // value because the receiver of an extension method of a type parameter cannot be an in parameter
        var receiverParameters = string.Join(", ", method.Parameters.Select((p, i) =>
            i == 0 ? $"this {Type(p.Type)} {p.Name}" : $"{RefKindText(p.RefKind)}{Type(p.Type)} {p.Name}"));

        var arguments = string.Join(", ", method.Parameters.Select(p =>
            p.RefKind == RefKind.Ref ? $"ref {p.Name}" : p.RefKind == RefKind.Out ? $"out {p.Name}" : p.Name));

        var target = $"{method.ContainingType.Name}.{method.Name}<{typeArguments}>";
        var cref = Cref(method);

        // the constraints of a type parameter of the marked member are the ones of the generated member, the
        // type of a single component that they carry is spelled out as well
        string Constraints(string indent)
        {
            var text = new StringBuilder();
            foreach (var typeParameter in typeParameters)
            {
                var parts = new List<string>();
                if (typeParameter.HasUnmanagedTypeConstraint) parts.Add("unmanaged");
                else if (typeParameter.HasValueTypeConstraint) parts.Add("struct");
                else if (typeParameter.HasReferenceTypeConstraint) parts.Add("class");
                foreach (var constraint in typeParameter.ConstraintTypes) parts.Add(Type(constraint));
                if (typeParameter.HasConstructorConstraint) parts.Add("new()");
                if (parts.Count == 0) continue;
                text.AppendLine();
                text.Append($"{indent}where {typeParameter.Name} : {string.Join(", ", parts)}");
            }
            return text.ToString();
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine($"namespace {Namespace};");
        sb.AppendLine();

        // the member the math class carries, the type of a single component is named where the member is called
        sb.AppendLine($"public static partial class ex_{scalar}");
        sb.AppendLine("{");
        sb.AppendLine("    extension(math)");
        sb.AppendLine("    {");
        sb.AppendLine($"        /// <inheritdoc cref=\"{cref}\"/>");
        sb.AppendLine($"        {Attr}");
        sb.AppendLine($"        public static {Type(method.ReturnType)} {method.Name}{typeParametersText}({parameters}){Constraints("            ")}");
        sb.AppendLine($"            => {target}({arguments});");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // the member the value itself carries, it reads like the member of a vector
        sb.AppendLine($"public static partial class math_ex_{scalar}");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <inheritdoc cref=\"{cref}\"/>");
        sb.AppendLine($"    {Attr}");
        sb.AppendLine($"    public static {Type(method.ReturnType)} {method.Name}{typeParametersText}({receiverParameters}){Constraints("        ")}");
        sb.AppendLine($"        => {target}({arguments});");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
