// generated by template, do not modify manually

namespace Coplt.Mathematics;

#region float2x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float2x2 asf([This] float2x2 v) => v.BitCast<float2x2, float2x2>();
    [MethodImpl(256 | 512)]
    public static int2x2 asi([This] float2x2 v) => v.BitCast<float2x2, int2x2>();
    [MethodImpl(256 | 512)]
    public static uint2x2 asu([This] float2x2 v) => v.BitCast<float2x2, uint2x2>();
    [MethodImpl(256 | 512)]
    public static b32m2x2 asb([This] float2x2 v) => v.BitCast<float2x2, b32m2x2>();
}

#endregion // float2x2

#region float2x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float2x3 asf([This] float2x3 v) => v.BitCast<float2x3, float2x3>();
    [MethodImpl(256 | 512)]
    public static int2x3 asi([This] float2x3 v) => v.BitCast<float2x3, int2x3>();
    [MethodImpl(256 | 512)]
    public static uint2x3 asu([This] float2x3 v) => v.BitCast<float2x3, uint2x3>();
    [MethodImpl(256 | 512)]
    public static b32m2x3 asb([This] float2x3 v) => v.BitCast<float2x3, b32m2x3>();
}

#endregion // float2x3

#region float2x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float2x4 asf([This] float2x4 v) => v.BitCast<float2x4, float2x4>();
    [MethodImpl(256 | 512)]
    public static int2x4 asi([This] float2x4 v) => v.BitCast<float2x4, int2x4>();
    [MethodImpl(256 | 512)]
    public static uint2x4 asu([This] float2x4 v) => v.BitCast<float2x4, uint2x4>();
    [MethodImpl(256 | 512)]
    public static b32m2x4 asb([This] float2x4 v) => v.BitCast<float2x4, b32m2x4>();
}

#endregion // float2x4

#region float3x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float3x2 asf([This] float3x2 v) => v.BitCast<float3x2, float3x2>();
    [MethodImpl(256 | 512)]
    public static int3x2 asi([This] float3x2 v) => v.BitCast<float3x2, int3x2>();
    [MethodImpl(256 | 512)]
    public static uint3x2 asu([This] float3x2 v) => v.BitCast<float3x2, uint3x2>();
    [MethodImpl(256 | 512)]
    public static b32m3x2 asb([This] float3x2 v) => v.BitCast<float3x2, b32m3x2>();
}

#endregion // float3x2

#region float3x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float3x3 asf([This] float3x3 v) => v.BitCast<float3x3, float3x3>();
    [MethodImpl(256 | 512)]
    public static int3x3 asi([This] float3x3 v) => v.BitCast<float3x3, int3x3>();
    [MethodImpl(256 | 512)]
    public static uint3x3 asu([This] float3x3 v) => v.BitCast<float3x3, uint3x3>();
    [MethodImpl(256 | 512)]
    public static b32m3x3 asb([This] float3x3 v) => v.BitCast<float3x3, b32m3x3>();
}

#endregion // float3x3

#region float3x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float3x4 asf([This] float3x4 v) => v.BitCast<float3x4, float3x4>();
    [MethodImpl(256 | 512)]
    public static int3x4 asi([This] float3x4 v) => v.BitCast<float3x4, int3x4>();
    [MethodImpl(256 | 512)]
    public static uint3x4 asu([This] float3x4 v) => v.BitCast<float3x4, uint3x4>();
    [MethodImpl(256 | 512)]
    public static b32m3x4 asb([This] float3x4 v) => v.BitCast<float3x4, b32m3x4>();
}

#endregion // float3x4

#region float4x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float4x2 asf([This] float4x2 v) => v.BitCast<float4x2, float4x2>();
    [MethodImpl(256 | 512)]
    public static int4x2 asi([This] float4x2 v) => v.BitCast<float4x2, int4x2>();
    [MethodImpl(256 | 512)]
    public static uint4x2 asu([This] float4x2 v) => v.BitCast<float4x2, uint4x2>();
    [MethodImpl(256 | 512)]
    public static b32m4x2 asb([This] float4x2 v) => v.BitCast<float4x2, b32m4x2>();
}

#endregion // float4x2

#region float4x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float4x3 asf([This] float4x3 v) => v.BitCast<float4x3, float4x3>();
    [MethodImpl(256 | 512)]
    public static int4x3 asi([This] float4x3 v) => v.BitCast<float4x3, int4x3>();
    [MethodImpl(256 | 512)]
    public static uint4x3 asu([This] float4x3 v) => v.BitCast<float4x3, uint4x3>();
    [MethodImpl(256 | 512)]
    public static b32m4x3 asb([This] float4x3 v) => v.BitCast<float4x3, b32m4x3>();
}

#endregion // float4x3

#region float4x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float4x4 asf([This] float4x4 v) => v.BitCast<float4x4, float4x4>();
    [MethodImpl(256 | 512)]
    public static int4x4 asi([This] float4x4 v) => v.BitCast<float4x4, int4x4>();
    [MethodImpl(256 | 512)]
    public static uint4x4 asu([This] float4x4 v) => v.BitCast<float4x4, uint4x4>();
    [MethodImpl(256 | 512)]
    public static b32m4x4 asb([This] float4x4 v) => v.BitCast<float4x4, b32m4x4>();
}

#endregion // float4x4

#region double2x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double2x2 asf([This] double2x2 v) => v.BitCast<double2x2, double2x2>();
    [MethodImpl(256 | 512)]
    public static long2x2 asi([This] double2x2 v) => v.BitCast<double2x2, long2x2>();
    [MethodImpl(256 | 512)]
    public static ulong2x2 asu([This] double2x2 v) => v.BitCast<double2x2, ulong2x2>();
    [MethodImpl(256 | 512)]
    public static b64m2x2 asb([This] double2x2 v) => v.BitCast<double2x2, b64m2x2>();
}

#endregion // double2x2

#region double2x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double2x3 asf([This] double2x3 v) => v.BitCast<double2x3, double2x3>();
    [MethodImpl(256 | 512)]
    public static long2x3 asi([This] double2x3 v) => v.BitCast<double2x3, long2x3>();
    [MethodImpl(256 | 512)]
    public static ulong2x3 asu([This] double2x3 v) => v.BitCast<double2x3, ulong2x3>();
    [MethodImpl(256 | 512)]
    public static b64m2x3 asb([This] double2x3 v) => v.BitCast<double2x3, b64m2x3>();
}

#endregion // double2x3

#region double2x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double2x4 asf([This] double2x4 v) => v.BitCast<double2x4, double2x4>();
    [MethodImpl(256 | 512)]
    public static long2x4 asi([This] double2x4 v) => v.BitCast<double2x4, long2x4>();
    [MethodImpl(256 | 512)]
    public static ulong2x4 asu([This] double2x4 v) => v.BitCast<double2x4, ulong2x4>();
    [MethodImpl(256 | 512)]
    public static b64m2x4 asb([This] double2x4 v) => v.BitCast<double2x4, b64m2x4>();
}

#endregion // double2x4

#region double3x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double3x2 asf([This] double3x2 v) => v.BitCast<double3x2, double3x2>();
    [MethodImpl(256 | 512)]
    public static long3x2 asi([This] double3x2 v) => v.BitCast<double3x2, long3x2>();
    [MethodImpl(256 | 512)]
    public static ulong3x2 asu([This] double3x2 v) => v.BitCast<double3x2, ulong3x2>();
    [MethodImpl(256 | 512)]
    public static b64m3x2 asb([This] double3x2 v) => v.BitCast<double3x2, b64m3x2>();
}

#endregion // double3x2

#region double3x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double3x3 asf([This] double3x3 v) => v.BitCast<double3x3, double3x3>();
    [MethodImpl(256 | 512)]
    public static long3x3 asi([This] double3x3 v) => v.BitCast<double3x3, long3x3>();
    [MethodImpl(256 | 512)]
    public static ulong3x3 asu([This] double3x3 v) => v.BitCast<double3x3, ulong3x3>();
    [MethodImpl(256 | 512)]
    public static b64m3x3 asb([This] double3x3 v) => v.BitCast<double3x3, b64m3x3>();
}

#endregion // double3x3

#region double3x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double3x4 asf([This] double3x4 v) => v.BitCast<double3x4, double3x4>();
    [MethodImpl(256 | 512)]
    public static long3x4 asi([This] double3x4 v) => v.BitCast<double3x4, long3x4>();
    [MethodImpl(256 | 512)]
    public static ulong3x4 asu([This] double3x4 v) => v.BitCast<double3x4, ulong3x4>();
    [MethodImpl(256 | 512)]
    public static b64m3x4 asb([This] double3x4 v) => v.BitCast<double3x4, b64m3x4>();
}

#endregion // double3x4

#region double4x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double4x2 asf([This] double4x2 v) => v.BitCast<double4x2, double4x2>();
    [MethodImpl(256 | 512)]
    public static long4x2 asi([This] double4x2 v) => v.BitCast<double4x2, long4x2>();
    [MethodImpl(256 | 512)]
    public static ulong4x2 asu([This] double4x2 v) => v.BitCast<double4x2, ulong4x2>();
    [MethodImpl(256 | 512)]
    public static b64m4x2 asb([This] double4x2 v) => v.BitCast<double4x2, b64m4x2>();
}

#endregion // double4x2

#region double4x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double4x3 asf([This] double4x3 v) => v.BitCast<double4x3, double4x3>();
    [MethodImpl(256 | 512)]
    public static long4x3 asi([This] double4x3 v) => v.BitCast<double4x3, long4x3>();
    [MethodImpl(256 | 512)]
    public static ulong4x3 asu([This] double4x3 v) => v.BitCast<double4x3, ulong4x3>();
    [MethodImpl(256 | 512)]
    public static b64m4x3 asb([This] double4x3 v) => v.BitCast<double4x3, b64m4x3>();
}

#endregion // double4x3

#region double4x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double4x4 asf([This] double4x4 v) => v.BitCast<double4x4, double4x4>();
    [MethodImpl(256 | 512)]
    public static long4x4 asi([This] double4x4 v) => v.BitCast<double4x4, long4x4>();
    [MethodImpl(256 | 512)]
    public static ulong4x4 asu([This] double4x4 v) => v.BitCast<double4x4, ulong4x4>();
    [MethodImpl(256 | 512)]
    public static b64m4x4 asb([This] double4x4 v) => v.BitCast<double4x4, b64m4x4>();
}

#endregion // double4x4

#region short2x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half2x2 asf([This] short2x2 v) => v.BitCast<short2x2, half2x2>();
    [MethodImpl(256 | 512)]
    public static short2x2 asi([This] short2x2 v) => v.BitCast<short2x2, short2x2>();
    [MethodImpl(256 | 512)]
    public static ushort2x2 asu([This] short2x2 v) => v.BitCast<short2x2, ushort2x2>();
    [MethodImpl(256 | 512)]
    public static b16m2x2 asb([This] short2x2 v) => v.BitCast<short2x2, b16m2x2>();
}

#endregion // short2x2

#region short2x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half2x3 asf([This] short2x3 v) => v.BitCast<short2x3, half2x3>();
    [MethodImpl(256 | 512)]
    public static short2x3 asi([This] short2x3 v) => v.BitCast<short2x3, short2x3>();
    [MethodImpl(256 | 512)]
    public static ushort2x3 asu([This] short2x3 v) => v.BitCast<short2x3, ushort2x3>();
    [MethodImpl(256 | 512)]
    public static b16m2x3 asb([This] short2x3 v) => v.BitCast<short2x3, b16m2x3>();
}

#endregion // short2x3

#region short2x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half2x4 asf([This] short2x4 v) => v.BitCast<short2x4, half2x4>();
    [MethodImpl(256 | 512)]
    public static short2x4 asi([This] short2x4 v) => v.BitCast<short2x4, short2x4>();
    [MethodImpl(256 | 512)]
    public static ushort2x4 asu([This] short2x4 v) => v.BitCast<short2x4, ushort2x4>();
    [MethodImpl(256 | 512)]
    public static b16m2x4 asb([This] short2x4 v) => v.BitCast<short2x4, b16m2x4>();
}

#endregion // short2x4

#region short3x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half3x2 asf([This] short3x2 v) => v.BitCast<short3x2, half3x2>();
    [MethodImpl(256 | 512)]
    public static short3x2 asi([This] short3x2 v) => v.BitCast<short3x2, short3x2>();
    [MethodImpl(256 | 512)]
    public static ushort3x2 asu([This] short3x2 v) => v.BitCast<short3x2, ushort3x2>();
    [MethodImpl(256 | 512)]
    public static b16m3x2 asb([This] short3x2 v) => v.BitCast<short3x2, b16m3x2>();
}

#endregion // short3x2

#region short3x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half3x3 asf([This] short3x3 v) => v.BitCast<short3x3, half3x3>();
    [MethodImpl(256 | 512)]
    public static short3x3 asi([This] short3x3 v) => v.BitCast<short3x3, short3x3>();
    [MethodImpl(256 | 512)]
    public static ushort3x3 asu([This] short3x3 v) => v.BitCast<short3x3, ushort3x3>();
    [MethodImpl(256 | 512)]
    public static b16m3x3 asb([This] short3x3 v) => v.BitCast<short3x3, b16m3x3>();
}

#endregion // short3x3

#region short3x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half3x4 asf([This] short3x4 v) => v.BitCast<short3x4, half3x4>();
    [MethodImpl(256 | 512)]
    public static short3x4 asi([This] short3x4 v) => v.BitCast<short3x4, short3x4>();
    [MethodImpl(256 | 512)]
    public static ushort3x4 asu([This] short3x4 v) => v.BitCast<short3x4, ushort3x4>();
    [MethodImpl(256 | 512)]
    public static b16m3x4 asb([This] short3x4 v) => v.BitCast<short3x4, b16m3x4>();
}

#endregion // short3x4

#region short4x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half4x2 asf([This] short4x2 v) => v.BitCast<short4x2, half4x2>();
    [MethodImpl(256 | 512)]
    public static short4x2 asi([This] short4x2 v) => v.BitCast<short4x2, short4x2>();
    [MethodImpl(256 | 512)]
    public static ushort4x2 asu([This] short4x2 v) => v.BitCast<short4x2, ushort4x2>();
    [MethodImpl(256 | 512)]
    public static b16m4x2 asb([This] short4x2 v) => v.BitCast<short4x2, b16m4x2>();
}

#endregion // short4x2

#region short4x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half4x3 asf([This] short4x3 v) => v.BitCast<short4x3, half4x3>();
    [MethodImpl(256 | 512)]
    public static short4x3 asi([This] short4x3 v) => v.BitCast<short4x3, short4x3>();
    [MethodImpl(256 | 512)]
    public static ushort4x3 asu([This] short4x3 v) => v.BitCast<short4x3, ushort4x3>();
    [MethodImpl(256 | 512)]
    public static b16m4x3 asb([This] short4x3 v) => v.BitCast<short4x3, b16m4x3>();
}

#endregion // short4x3

#region short4x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half4x4 asf([This] short4x4 v) => v.BitCast<short4x4, half4x4>();
    [MethodImpl(256 | 512)]
    public static short4x4 asi([This] short4x4 v) => v.BitCast<short4x4, short4x4>();
    [MethodImpl(256 | 512)]
    public static ushort4x4 asu([This] short4x4 v) => v.BitCast<short4x4, ushort4x4>();
    [MethodImpl(256 | 512)]
    public static b16m4x4 asb([This] short4x4 v) => v.BitCast<short4x4, b16m4x4>();
}

#endregion // short4x4

#region ushort2x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half2x2 asf([This] ushort2x2 v) => v.BitCast<ushort2x2, half2x2>();
    [MethodImpl(256 | 512)]
    public static short2x2 asi([This] ushort2x2 v) => v.BitCast<ushort2x2, short2x2>();
    [MethodImpl(256 | 512)]
    public static ushort2x2 asu([This] ushort2x2 v) => v.BitCast<ushort2x2, ushort2x2>();
    [MethodImpl(256 | 512)]
    public static b16m2x2 asb([This] ushort2x2 v) => v.BitCast<ushort2x2, b16m2x2>();
}

#endregion // ushort2x2

#region ushort2x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half2x3 asf([This] ushort2x3 v) => v.BitCast<ushort2x3, half2x3>();
    [MethodImpl(256 | 512)]
    public static short2x3 asi([This] ushort2x3 v) => v.BitCast<ushort2x3, short2x3>();
    [MethodImpl(256 | 512)]
    public static ushort2x3 asu([This] ushort2x3 v) => v.BitCast<ushort2x3, ushort2x3>();
    [MethodImpl(256 | 512)]
    public static b16m2x3 asb([This] ushort2x3 v) => v.BitCast<ushort2x3, b16m2x3>();
}

#endregion // ushort2x3

#region ushort2x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half2x4 asf([This] ushort2x4 v) => v.BitCast<ushort2x4, half2x4>();
    [MethodImpl(256 | 512)]
    public static short2x4 asi([This] ushort2x4 v) => v.BitCast<ushort2x4, short2x4>();
    [MethodImpl(256 | 512)]
    public static ushort2x4 asu([This] ushort2x4 v) => v.BitCast<ushort2x4, ushort2x4>();
    [MethodImpl(256 | 512)]
    public static b16m2x4 asb([This] ushort2x4 v) => v.BitCast<ushort2x4, b16m2x4>();
}

#endregion // ushort2x4

#region ushort3x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half3x2 asf([This] ushort3x2 v) => v.BitCast<ushort3x2, half3x2>();
    [MethodImpl(256 | 512)]
    public static short3x2 asi([This] ushort3x2 v) => v.BitCast<ushort3x2, short3x2>();
    [MethodImpl(256 | 512)]
    public static ushort3x2 asu([This] ushort3x2 v) => v.BitCast<ushort3x2, ushort3x2>();
    [MethodImpl(256 | 512)]
    public static b16m3x2 asb([This] ushort3x2 v) => v.BitCast<ushort3x2, b16m3x2>();
}

#endregion // ushort3x2

#region ushort3x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half3x3 asf([This] ushort3x3 v) => v.BitCast<ushort3x3, half3x3>();
    [MethodImpl(256 | 512)]
    public static short3x3 asi([This] ushort3x3 v) => v.BitCast<ushort3x3, short3x3>();
    [MethodImpl(256 | 512)]
    public static ushort3x3 asu([This] ushort3x3 v) => v.BitCast<ushort3x3, ushort3x3>();
    [MethodImpl(256 | 512)]
    public static b16m3x3 asb([This] ushort3x3 v) => v.BitCast<ushort3x3, b16m3x3>();
}

#endregion // ushort3x3

#region ushort3x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half3x4 asf([This] ushort3x4 v) => v.BitCast<ushort3x4, half3x4>();
    [MethodImpl(256 | 512)]
    public static short3x4 asi([This] ushort3x4 v) => v.BitCast<ushort3x4, short3x4>();
    [MethodImpl(256 | 512)]
    public static ushort3x4 asu([This] ushort3x4 v) => v.BitCast<ushort3x4, ushort3x4>();
    [MethodImpl(256 | 512)]
    public static b16m3x4 asb([This] ushort3x4 v) => v.BitCast<ushort3x4, b16m3x4>();
}

#endregion // ushort3x4

#region ushort4x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half4x2 asf([This] ushort4x2 v) => v.BitCast<ushort4x2, half4x2>();
    [MethodImpl(256 | 512)]
    public static short4x2 asi([This] ushort4x2 v) => v.BitCast<ushort4x2, short4x2>();
    [MethodImpl(256 | 512)]
    public static ushort4x2 asu([This] ushort4x2 v) => v.BitCast<ushort4x2, ushort4x2>();
    [MethodImpl(256 | 512)]
    public static b16m4x2 asb([This] ushort4x2 v) => v.BitCast<ushort4x2, b16m4x2>();
}

#endregion // ushort4x2

#region ushort4x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half4x3 asf([This] ushort4x3 v) => v.BitCast<ushort4x3, half4x3>();
    [MethodImpl(256 | 512)]
    public static short4x3 asi([This] ushort4x3 v) => v.BitCast<ushort4x3, short4x3>();
    [MethodImpl(256 | 512)]
    public static ushort4x3 asu([This] ushort4x3 v) => v.BitCast<ushort4x3, ushort4x3>();
    [MethodImpl(256 | 512)]
    public static b16m4x3 asb([This] ushort4x3 v) => v.BitCast<ushort4x3, b16m4x3>();
}

#endregion // ushort4x3

#region ushort4x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half4x4 asf([This] ushort4x4 v) => v.BitCast<ushort4x4, half4x4>();
    [MethodImpl(256 | 512)]
    public static short4x4 asi([This] ushort4x4 v) => v.BitCast<ushort4x4, short4x4>();
    [MethodImpl(256 | 512)]
    public static ushort4x4 asu([This] ushort4x4 v) => v.BitCast<ushort4x4, ushort4x4>();
    [MethodImpl(256 | 512)]
    public static b16m4x4 asb([This] ushort4x4 v) => v.BitCast<ushort4x4, b16m4x4>();
}

#endregion // ushort4x4

#region int2x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float2x2 asf([This] int2x2 v) => v.BitCast<int2x2, float2x2>();
    [MethodImpl(256 | 512)]
    public static int2x2 asi([This] int2x2 v) => v.BitCast<int2x2, int2x2>();
    [MethodImpl(256 | 512)]
    public static uint2x2 asu([This] int2x2 v) => v.BitCast<int2x2, uint2x2>();
    [MethodImpl(256 | 512)]
    public static b32m2x2 asb([This] int2x2 v) => v.BitCast<int2x2, b32m2x2>();
}

#endregion // int2x2

#region int2x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float2x3 asf([This] int2x3 v) => v.BitCast<int2x3, float2x3>();
    [MethodImpl(256 | 512)]
    public static int2x3 asi([This] int2x3 v) => v.BitCast<int2x3, int2x3>();
    [MethodImpl(256 | 512)]
    public static uint2x3 asu([This] int2x3 v) => v.BitCast<int2x3, uint2x3>();
    [MethodImpl(256 | 512)]
    public static b32m2x3 asb([This] int2x3 v) => v.BitCast<int2x3, b32m2x3>();
}

#endregion // int2x3

#region int2x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float2x4 asf([This] int2x4 v) => v.BitCast<int2x4, float2x4>();
    [MethodImpl(256 | 512)]
    public static int2x4 asi([This] int2x4 v) => v.BitCast<int2x4, int2x4>();
    [MethodImpl(256 | 512)]
    public static uint2x4 asu([This] int2x4 v) => v.BitCast<int2x4, uint2x4>();
    [MethodImpl(256 | 512)]
    public static b32m2x4 asb([This] int2x4 v) => v.BitCast<int2x4, b32m2x4>();
}

#endregion // int2x4

#region int3x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float3x2 asf([This] int3x2 v) => v.BitCast<int3x2, float3x2>();
    [MethodImpl(256 | 512)]
    public static int3x2 asi([This] int3x2 v) => v.BitCast<int3x2, int3x2>();
    [MethodImpl(256 | 512)]
    public static uint3x2 asu([This] int3x2 v) => v.BitCast<int3x2, uint3x2>();
    [MethodImpl(256 | 512)]
    public static b32m3x2 asb([This] int3x2 v) => v.BitCast<int3x2, b32m3x2>();
}

#endregion // int3x2

#region int3x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float3x3 asf([This] int3x3 v) => v.BitCast<int3x3, float3x3>();
    [MethodImpl(256 | 512)]
    public static int3x3 asi([This] int3x3 v) => v.BitCast<int3x3, int3x3>();
    [MethodImpl(256 | 512)]
    public static uint3x3 asu([This] int3x3 v) => v.BitCast<int3x3, uint3x3>();
    [MethodImpl(256 | 512)]
    public static b32m3x3 asb([This] int3x3 v) => v.BitCast<int3x3, b32m3x3>();
}

#endregion // int3x3

#region int3x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float3x4 asf([This] int3x4 v) => v.BitCast<int3x4, float3x4>();
    [MethodImpl(256 | 512)]
    public static int3x4 asi([This] int3x4 v) => v.BitCast<int3x4, int3x4>();
    [MethodImpl(256 | 512)]
    public static uint3x4 asu([This] int3x4 v) => v.BitCast<int3x4, uint3x4>();
    [MethodImpl(256 | 512)]
    public static b32m3x4 asb([This] int3x4 v) => v.BitCast<int3x4, b32m3x4>();
}

#endregion // int3x4

#region int4x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float4x2 asf([This] int4x2 v) => v.BitCast<int4x2, float4x2>();
    [MethodImpl(256 | 512)]
    public static int4x2 asi([This] int4x2 v) => v.BitCast<int4x2, int4x2>();
    [MethodImpl(256 | 512)]
    public static uint4x2 asu([This] int4x2 v) => v.BitCast<int4x2, uint4x2>();
    [MethodImpl(256 | 512)]
    public static b32m4x2 asb([This] int4x2 v) => v.BitCast<int4x2, b32m4x2>();
}

#endregion // int4x2

#region int4x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float4x3 asf([This] int4x3 v) => v.BitCast<int4x3, float4x3>();
    [MethodImpl(256 | 512)]
    public static int4x3 asi([This] int4x3 v) => v.BitCast<int4x3, int4x3>();
    [MethodImpl(256 | 512)]
    public static uint4x3 asu([This] int4x3 v) => v.BitCast<int4x3, uint4x3>();
    [MethodImpl(256 | 512)]
    public static b32m4x3 asb([This] int4x3 v) => v.BitCast<int4x3, b32m4x3>();
}

#endregion // int4x3

#region int4x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float4x4 asf([This] int4x4 v) => v.BitCast<int4x4, float4x4>();
    [MethodImpl(256 | 512)]
    public static int4x4 asi([This] int4x4 v) => v.BitCast<int4x4, int4x4>();
    [MethodImpl(256 | 512)]
    public static uint4x4 asu([This] int4x4 v) => v.BitCast<int4x4, uint4x4>();
    [MethodImpl(256 | 512)]
    public static b32m4x4 asb([This] int4x4 v) => v.BitCast<int4x4, b32m4x4>();
}

#endregion // int4x4

#region uint2x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float2x2 asf([This] uint2x2 v) => v.BitCast<uint2x2, float2x2>();
    [MethodImpl(256 | 512)]
    public static int2x2 asi([This] uint2x2 v) => v.BitCast<uint2x2, int2x2>();
    [MethodImpl(256 | 512)]
    public static uint2x2 asu([This] uint2x2 v) => v.BitCast<uint2x2, uint2x2>();
    [MethodImpl(256 | 512)]
    public static b32m2x2 asb([This] uint2x2 v) => v.BitCast<uint2x2, b32m2x2>();
}

#endregion // uint2x2

#region uint2x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float2x3 asf([This] uint2x3 v) => v.BitCast<uint2x3, float2x3>();
    [MethodImpl(256 | 512)]
    public static int2x3 asi([This] uint2x3 v) => v.BitCast<uint2x3, int2x3>();
    [MethodImpl(256 | 512)]
    public static uint2x3 asu([This] uint2x3 v) => v.BitCast<uint2x3, uint2x3>();
    [MethodImpl(256 | 512)]
    public static b32m2x3 asb([This] uint2x3 v) => v.BitCast<uint2x3, b32m2x3>();
}

#endregion // uint2x3

#region uint2x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float2x4 asf([This] uint2x4 v) => v.BitCast<uint2x4, float2x4>();
    [MethodImpl(256 | 512)]
    public static int2x4 asi([This] uint2x4 v) => v.BitCast<uint2x4, int2x4>();
    [MethodImpl(256 | 512)]
    public static uint2x4 asu([This] uint2x4 v) => v.BitCast<uint2x4, uint2x4>();
    [MethodImpl(256 | 512)]
    public static b32m2x4 asb([This] uint2x4 v) => v.BitCast<uint2x4, b32m2x4>();
}

#endregion // uint2x4

#region uint3x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float3x2 asf([This] uint3x2 v) => v.BitCast<uint3x2, float3x2>();
    [MethodImpl(256 | 512)]
    public static int3x2 asi([This] uint3x2 v) => v.BitCast<uint3x2, int3x2>();
    [MethodImpl(256 | 512)]
    public static uint3x2 asu([This] uint3x2 v) => v.BitCast<uint3x2, uint3x2>();
    [MethodImpl(256 | 512)]
    public static b32m3x2 asb([This] uint3x2 v) => v.BitCast<uint3x2, b32m3x2>();
}

#endregion // uint3x2

#region uint3x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float3x3 asf([This] uint3x3 v) => v.BitCast<uint3x3, float3x3>();
    [MethodImpl(256 | 512)]
    public static int3x3 asi([This] uint3x3 v) => v.BitCast<uint3x3, int3x3>();
    [MethodImpl(256 | 512)]
    public static uint3x3 asu([This] uint3x3 v) => v.BitCast<uint3x3, uint3x3>();
    [MethodImpl(256 | 512)]
    public static b32m3x3 asb([This] uint3x3 v) => v.BitCast<uint3x3, b32m3x3>();
}

#endregion // uint3x3

#region uint3x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float3x4 asf([This] uint3x4 v) => v.BitCast<uint3x4, float3x4>();
    [MethodImpl(256 | 512)]
    public static int3x4 asi([This] uint3x4 v) => v.BitCast<uint3x4, int3x4>();
    [MethodImpl(256 | 512)]
    public static uint3x4 asu([This] uint3x4 v) => v.BitCast<uint3x4, uint3x4>();
    [MethodImpl(256 | 512)]
    public static b32m3x4 asb([This] uint3x4 v) => v.BitCast<uint3x4, b32m3x4>();
}

#endregion // uint3x4

#region uint4x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float4x2 asf([This] uint4x2 v) => v.BitCast<uint4x2, float4x2>();
    [MethodImpl(256 | 512)]
    public static int4x2 asi([This] uint4x2 v) => v.BitCast<uint4x2, int4x2>();
    [MethodImpl(256 | 512)]
    public static uint4x2 asu([This] uint4x2 v) => v.BitCast<uint4x2, uint4x2>();
    [MethodImpl(256 | 512)]
    public static b32m4x2 asb([This] uint4x2 v) => v.BitCast<uint4x2, b32m4x2>();
}

#endregion // uint4x2

#region uint4x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float4x3 asf([This] uint4x3 v) => v.BitCast<uint4x3, float4x3>();
    [MethodImpl(256 | 512)]
    public static int4x3 asi([This] uint4x3 v) => v.BitCast<uint4x3, int4x3>();
    [MethodImpl(256 | 512)]
    public static uint4x3 asu([This] uint4x3 v) => v.BitCast<uint4x3, uint4x3>();
    [MethodImpl(256 | 512)]
    public static b32m4x3 asb([This] uint4x3 v) => v.BitCast<uint4x3, b32m4x3>();
}

#endregion // uint4x3

#region uint4x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float4x4 asf([This] uint4x4 v) => v.BitCast<uint4x4, float4x4>();
    [MethodImpl(256 | 512)]
    public static int4x4 asi([This] uint4x4 v) => v.BitCast<uint4x4, int4x4>();
    [MethodImpl(256 | 512)]
    public static uint4x4 asu([This] uint4x4 v) => v.BitCast<uint4x4, uint4x4>();
    [MethodImpl(256 | 512)]
    public static b32m4x4 asb([This] uint4x4 v) => v.BitCast<uint4x4, b32m4x4>();
}

#endregion // uint4x4

#region long2x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double2x2 asf([This] long2x2 v) => v.BitCast<long2x2, double2x2>();
    [MethodImpl(256 | 512)]
    public static long2x2 asi([This] long2x2 v) => v.BitCast<long2x2, long2x2>();
    [MethodImpl(256 | 512)]
    public static ulong2x2 asu([This] long2x2 v) => v.BitCast<long2x2, ulong2x2>();
    [MethodImpl(256 | 512)]
    public static b64m2x2 asb([This] long2x2 v) => v.BitCast<long2x2, b64m2x2>();
}

#endregion // long2x2

#region long2x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double2x3 asf([This] long2x3 v) => v.BitCast<long2x3, double2x3>();
    [MethodImpl(256 | 512)]
    public static long2x3 asi([This] long2x3 v) => v.BitCast<long2x3, long2x3>();
    [MethodImpl(256 | 512)]
    public static ulong2x3 asu([This] long2x3 v) => v.BitCast<long2x3, ulong2x3>();
    [MethodImpl(256 | 512)]
    public static b64m2x3 asb([This] long2x3 v) => v.BitCast<long2x3, b64m2x3>();
}

#endregion // long2x3

#region long2x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double2x4 asf([This] long2x4 v) => v.BitCast<long2x4, double2x4>();
    [MethodImpl(256 | 512)]
    public static long2x4 asi([This] long2x4 v) => v.BitCast<long2x4, long2x4>();
    [MethodImpl(256 | 512)]
    public static ulong2x4 asu([This] long2x4 v) => v.BitCast<long2x4, ulong2x4>();
    [MethodImpl(256 | 512)]
    public static b64m2x4 asb([This] long2x4 v) => v.BitCast<long2x4, b64m2x4>();
}

#endregion // long2x4

#region long3x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double3x2 asf([This] long3x2 v) => v.BitCast<long3x2, double3x2>();
    [MethodImpl(256 | 512)]
    public static long3x2 asi([This] long3x2 v) => v.BitCast<long3x2, long3x2>();
    [MethodImpl(256 | 512)]
    public static ulong3x2 asu([This] long3x2 v) => v.BitCast<long3x2, ulong3x2>();
    [MethodImpl(256 | 512)]
    public static b64m3x2 asb([This] long3x2 v) => v.BitCast<long3x2, b64m3x2>();
}

#endregion // long3x2

#region long3x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double3x3 asf([This] long3x3 v) => v.BitCast<long3x3, double3x3>();
    [MethodImpl(256 | 512)]
    public static long3x3 asi([This] long3x3 v) => v.BitCast<long3x3, long3x3>();
    [MethodImpl(256 | 512)]
    public static ulong3x3 asu([This] long3x3 v) => v.BitCast<long3x3, ulong3x3>();
    [MethodImpl(256 | 512)]
    public static b64m3x3 asb([This] long3x3 v) => v.BitCast<long3x3, b64m3x3>();
}

#endregion // long3x3

#region long3x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double3x4 asf([This] long3x4 v) => v.BitCast<long3x4, double3x4>();
    [MethodImpl(256 | 512)]
    public static long3x4 asi([This] long3x4 v) => v.BitCast<long3x4, long3x4>();
    [MethodImpl(256 | 512)]
    public static ulong3x4 asu([This] long3x4 v) => v.BitCast<long3x4, ulong3x4>();
    [MethodImpl(256 | 512)]
    public static b64m3x4 asb([This] long3x4 v) => v.BitCast<long3x4, b64m3x4>();
}

#endregion // long3x4

#region long4x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double4x2 asf([This] long4x2 v) => v.BitCast<long4x2, double4x2>();
    [MethodImpl(256 | 512)]
    public static long4x2 asi([This] long4x2 v) => v.BitCast<long4x2, long4x2>();
    [MethodImpl(256 | 512)]
    public static ulong4x2 asu([This] long4x2 v) => v.BitCast<long4x2, ulong4x2>();
    [MethodImpl(256 | 512)]
    public static b64m4x2 asb([This] long4x2 v) => v.BitCast<long4x2, b64m4x2>();
}

#endregion // long4x2

#region long4x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double4x3 asf([This] long4x3 v) => v.BitCast<long4x3, double4x3>();
    [MethodImpl(256 | 512)]
    public static long4x3 asi([This] long4x3 v) => v.BitCast<long4x3, long4x3>();
    [MethodImpl(256 | 512)]
    public static ulong4x3 asu([This] long4x3 v) => v.BitCast<long4x3, ulong4x3>();
    [MethodImpl(256 | 512)]
    public static b64m4x3 asb([This] long4x3 v) => v.BitCast<long4x3, b64m4x3>();
}

#endregion // long4x3

#region long4x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double4x4 asf([This] long4x4 v) => v.BitCast<long4x4, double4x4>();
    [MethodImpl(256 | 512)]
    public static long4x4 asi([This] long4x4 v) => v.BitCast<long4x4, long4x4>();
    [MethodImpl(256 | 512)]
    public static ulong4x4 asu([This] long4x4 v) => v.BitCast<long4x4, ulong4x4>();
    [MethodImpl(256 | 512)]
    public static b64m4x4 asb([This] long4x4 v) => v.BitCast<long4x4, b64m4x4>();
}

#endregion // long4x4

#region ulong2x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double2x2 asf([This] ulong2x2 v) => v.BitCast<ulong2x2, double2x2>();
    [MethodImpl(256 | 512)]
    public static long2x2 asi([This] ulong2x2 v) => v.BitCast<ulong2x2, long2x2>();
    [MethodImpl(256 | 512)]
    public static ulong2x2 asu([This] ulong2x2 v) => v.BitCast<ulong2x2, ulong2x2>();
    [MethodImpl(256 | 512)]
    public static b64m2x2 asb([This] ulong2x2 v) => v.BitCast<ulong2x2, b64m2x2>();
}

#endregion // ulong2x2

#region ulong2x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double2x3 asf([This] ulong2x3 v) => v.BitCast<ulong2x3, double2x3>();
    [MethodImpl(256 | 512)]
    public static long2x3 asi([This] ulong2x3 v) => v.BitCast<ulong2x3, long2x3>();
    [MethodImpl(256 | 512)]
    public static ulong2x3 asu([This] ulong2x3 v) => v.BitCast<ulong2x3, ulong2x3>();
    [MethodImpl(256 | 512)]
    public static b64m2x3 asb([This] ulong2x3 v) => v.BitCast<ulong2x3, b64m2x3>();
}

#endregion // ulong2x3

#region ulong2x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double2x4 asf([This] ulong2x4 v) => v.BitCast<ulong2x4, double2x4>();
    [MethodImpl(256 | 512)]
    public static long2x4 asi([This] ulong2x4 v) => v.BitCast<ulong2x4, long2x4>();
    [MethodImpl(256 | 512)]
    public static ulong2x4 asu([This] ulong2x4 v) => v.BitCast<ulong2x4, ulong2x4>();
    [MethodImpl(256 | 512)]
    public static b64m2x4 asb([This] ulong2x4 v) => v.BitCast<ulong2x4, b64m2x4>();
}

#endregion // ulong2x4

#region ulong3x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double3x2 asf([This] ulong3x2 v) => v.BitCast<ulong3x2, double3x2>();
    [MethodImpl(256 | 512)]
    public static long3x2 asi([This] ulong3x2 v) => v.BitCast<ulong3x2, long3x2>();
    [MethodImpl(256 | 512)]
    public static ulong3x2 asu([This] ulong3x2 v) => v.BitCast<ulong3x2, ulong3x2>();
    [MethodImpl(256 | 512)]
    public static b64m3x2 asb([This] ulong3x2 v) => v.BitCast<ulong3x2, b64m3x2>();
}

#endregion // ulong3x2

#region ulong3x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double3x3 asf([This] ulong3x3 v) => v.BitCast<ulong3x3, double3x3>();
    [MethodImpl(256 | 512)]
    public static long3x3 asi([This] ulong3x3 v) => v.BitCast<ulong3x3, long3x3>();
    [MethodImpl(256 | 512)]
    public static ulong3x3 asu([This] ulong3x3 v) => v.BitCast<ulong3x3, ulong3x3>();
    [MethodImpl(256 | 512)]
    public static b64m3x3 asb([This] ulong3x3 v) => v.BitCast<ulong3x3, b64m3x3>();
}

#endregion // ulong3x3

#region ulong3x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double3x4 asf([This] ulong3x4 v) => v.BitCast<ulong3x4, double3x4>();
    [MethodImpl(256 | 512)]
    public static long3x4 asi([This] ulong3x4 v) => v.BitCast<ulong3x4, long3x4>();
    [MethodImpl(256 | 512)]
    public static ulong3x4 asu([This] ulong3x4 v) => v.BitCast<ulong3x4, ulong3x4>();
    [MethodImpl(256 | 512)]
    public static b64m3x4 asb([This] ulong3x4 v) => v.BitCast<ulong3x4, b64m3x4>();
}

#endregion // ulong3x4

#region ulong4x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double4x2 asf([This] ulong4x2 v) => v.BitCast<ulong4x2, double4x2>();
    [MethodImpl(256 | 512)]
    public static long4x2 asi([This] ulong4x2 v) => v.BitCast<ulong4x2, long4x2>();
    [MethodImpl(256 | 512)]
    public static ulong4x2 asu([This] ulong4x2 v) => v.BitCast<ulong4x2, ulong4x2>();
    [MethodImpl(256 | 512)]
    public static b64m4x2 asb([This] ulong4x2 v) => v.BitCast<ulong4x2, b64m4x2>();
}

#endregion // ulong4x2

#region ulong4x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double4x3 asf([This] ulong4x3 v) => v.BitCast<ulong4x3, double4x3>();
    [MethodImpl(256 | 512)]
    public static long4x3 asi([This] ulong4x3 v) => v.BitCast<ulong4x3, long4x3>();
    [MethodImpl(256 | 512)]
    public static ulong4x3 asu([This] ulong4x3 v) => v.BitCast<ulong4x3, ulong4x3>();
    [MethodImpl(256 | 512)]
    public static b64m4x3 asb([This] ulong4x3 v) => v.BitCast<ulong4x3, b64m4x3>();
}

#endregion // ulong4x3

#region ulong4x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double4x4 asf([This] ulong4x4 v) => v.BitCast<ulong4x4, double4x4>();
    [MethodImpl(256 | 512)]
    public static long4x4 asi([This] ulong4x4 v) => v.BitCast<ulong4x4, long4x4>();
    [MethodImpl(256 | 512)]
    public static ulong4x4 asu([This] ulong4x4 v) => v.BitCast<ulong4x4, ulong4x4>();
    [MethodImpl(256 | 512)]
    public static b64m4x4 asb([This] ulong4x4 v) => v.BitCast<ulong4x4, b64m4x4>();
}

#endregion // ulong4x4

#region decimal2x2

[Ex]
public static partial class math
{
}

#endregion // decimal2x2

#region decimal2x3

[Ex]
public static partial class math
{
}

#endregion // decimal2x3

#region decimal2x4

[Ex]
public static partial class math
{
}

#endregion // decimal2x4

#region decimal3x2

[Ex]
public static partial class math
{
}

#endregion // decimal3x2

#region decimal3x3

[Ex]
public static partial class math
{
}

#endregion // decimal3x3

#region decimal3x4

[Ex]
public static partial class math
{
}

#endregion // decimal3x4

#region decimal4x2

[Ex]
public static partial class math
{
}

#endregion // decimal4x2

#region decimal4x3

[Ex]
public static partial class math
{
}

#endregion // decimal4x3

#region decimal4x4

[Ex]
public static partial class math
{
}

#endregion // decimal4x4

#region half2x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half2x2 asf([This] half2x2 v) => v.BitCast<half2x2, half2x2>();
    [MethodImpl(256 | 512)]
    public static short2x2 asi([This] half2x2 v) => v.BitCast<half2x2, short2x2>();
    [MethodImpl(256 | 512)]
    public static ushort2x2 asu([This] half2x2 v) => v.BitCast<half2x2, ushort2x2>();
    [MethodImpl(256 | 512)]
    public static b16m2x2 asb([This] half2x2 v) => v.BitCast<half2x2, b16m2x2>();
}

#endregion // half2x2

#region half2x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half2x3 asf([This] half2x3 v) => v.BitCast<half2x3, half2x3>();
    [MethodImpl(256 | 512)]
    public static short2x3 asi([This] half2x3 v) => v.BitCast<half2x3, short2x3>();
    [MethodImpl(256 | 512)]
    public static ushort2x3 asu([This] half2x3 v) => v.BitCast<half2x3, ushort2x3>();
    [MethodImpl(256 | 512)]
    public static b16m2x3 asb([This] half2x3 v) => v.BitCast<half2x3, b16m2x3>();
}

#endregion // half2x3

#region half2x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half2x4 asf([This] half2x4 v) => v.BitCast<half2x4, half2x4>();
    [MethodImpl(256 | 512)]
    public static short2x4 asi([This] half2x4 v) => v.BitCast<half2x4, short2x4>();
    [MethodImpl(256 | 512)]
    public static ushort2x4 asu([This] half2x4 v) => v.BitCast<half2x4, ushort2x4>();
    [MethodImpl(256 | 512)]
    public static b16m2x4 asb([This] half2x4 v) => v.BitCast<half2x4, b16m2x4>();
}

#endregion // half2x4

#region half3x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half3x2 asf([This] half3x2 v) => v.BitCast<half3x2, half3x2>();
    [MethodImpl(256 | 512)]
    public static short3x2 asi([This] half3x2 v) => v.BitCast<half3x2, short3x2>();
    [MethodImpl(256 | 512)]
    public static ushort3x2 asu([This] half3x2 v) => v.BitCast<half3x2, ushort3x2>();
    [MethodImpl(256 | 512)]
    public static b16m3x2 asb([This] half3x2 v) => v.BitCast<half3x2, b16m3x2>();
}

#endregion // half3x2

#region half3x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half3x3 asf([This] half3x3 v) => v.BitCast<half3x3, half3x3>();
    [MethodImpl(256 | 512)]
    public static short3x3 asi([This] half3x3 v) => v.BitCast<half3x3, short3x3>();
    [MethodImpl(256 | 512)]
    public static ushort3x3 asu([This] half3x3 v) => v.BitCast<half3x3, ushort3x3>();
    [MethodImpl(256 | 512)]
    public static b16m3x3 asb([This] half3x3 v) => v.BitCast<half3x3, b16m3x3>();
}

#endregion // half3x3

#region half3x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half3x4 asf([This] half3x4 v) => v.BitCast<half3x4, half3x4>();
    [MethodImpl(256 | 512)]
    public static short3x4 asi([This] half3x4 v) => v.BitCast<half3x4, short3x4>();
    [MethodImpl(256 | 512)]
    public static ushort3x4 asu([This] half3x4 v) => v.BitCast<half3x4, ushort3x4>();
    [MethodImpl(256 | 512)]
    public static b16m3x4 asb([This] half3x4 v) => v.BitCast<half3x4, b16m3x4>();
}

#endregion // half3x4

#region half4x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half4x2 asf([This] half4x2 v) => v.BitCast<half4x2, half4x2>();
    [MethodImpl(256 | 512)]
    public static short4x2 asi([This] half4x2 v) => v.BitCast<half4x2, short4x2>();
    [MethodImpl(256 | 512)]
    public static ushort4x2 asu([This] half4x2 v) => v.BitCast<half4x2, ushort4x2>();
    [MethodImpl(256 | 512)]
    public static b16m4x2 asb([This] half4x2 v) => v.BitCast<half4x2, b16m4x2>();
}

#endregion // half4x2

#region half4x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half4x3 asf([This] half4x3 v) => v.BitCast<half4x3, half4x3>();
    [MethodImpl(256 | 512)]
    public static short4x3 asi([This] half4x3 v) => v.BitCast<half4x3, short4x3>();
    [MethodImpl(256 | 512)]
    public static ushort4x3 asu([This] half4x3 v) => v.BitCast<half4x3, ushort4x3>();
    [MethodImpl(256 | 512)]
    public static b16m4x3 asb([This] half4x3 v) => v.BitCast<half4x3, b16m4x3>();
}

#endregion // half4x3

#region half4x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half4x4 asf([This] half4x4 v) => v.BitCast<half4x4, half4x4>();
    [MethodImpl(256 | 512)]
    public static short4x4 asi([This] half4x4 v) => v.BitCast<half4x4, short4x4>();
    [MethodImpl(256 | 512)]
    public static ushort4x4 asu([This] half4x4 v) => v.BitCast<half4x4, ushort4x4>();
    [MethodImpl(256 | 512)]
    public static b16m4x4 asb([This] half4x4 v) => v.BitCast<half4x4, b16m4x4>();
}

#endregion // half4x4

#region b16m2x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half2x2 asf([This] b16m2x2 v) => v.BitCast<b16m2x2, half2x2>();
    [MethodImpl(256 | 512)]
    public static short2x2 asi([This] b16m2x2 v) => v.BitCast<b16m2x2, short2x2>();
    [MethodImpl(256 | 512)]
    public static ushort2x2 asu([This] b16m2x2 v) => v.BitCast<b16m2x2, ushort2x2>();
    [MethodImpl(256 | 512)]
    public static b16m2x2 asb([This] b16m2x2 v) => v.BitCast<b16m2x2, b16m2x2>();
}

#endregion // b16m2x2

#region b16m2x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half2x3 asf([This] b16m2x3 v) => v.BitCast<b16m2x3, half2x3>();
    [MethodImpl(256 | 512)]
    public static short2x3 asi([This] b16m2x3 v) => v.BitCast<b16m2x3, short2x3>();
    [MethodImpl(256 | 512)]
    public static ushort2x3 asu([This] b16m2x3 v) => v.BitCast<b16m2x3, ushort2x3>();
    [MethodImpl(256 | 512)]
    public static b16m2x3 asb([This] b16m2x3 v) => v.BitCast<b16m2x3, b16m2x3>();
}

#endregion // b16m2x3

#region b16m2x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half2x4 asf([This] b16m2x4 v) => v.BitCast<b16m2x4, half2x4>();
    [MethodImpl(256 | 512)]
    public static short2x4 asi([This] b16m2x4 v) => v.BitCast<b16m2x4, short2x4>();
    [MethodImpl(256 | 512)]
    public static ushort2x4 asu([This] b16m2x4 v) => v.BitCast<b16m2x4, ushort2x4>();
    [MethodImpl(256 | 512)]
    public static b16m2x4 asb([This] b16m2x4 v) => v.BitCast<b16m2x4, b16m2x4>();
}

#endregion // b16m2x4

#region b16m3x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half3x2 asf([This] b16m3x2 v) => v.BitCast<b16m3x2, half3x2>();
    [MethodImpl(256 | 512)]
    public static short3x2 asi([This] b16m3x2 v) => v.BitCast<b16m3x2, short3x2>();
    [MethodImpl(256 | 512)]
    public static ushort3x2 asu([This] b16m3x2 v) => v.BitCast<b16m3x2, ushort3x2>();
    [MethodImpl(256 | 512)]
    public static b16m3x2 asb([This] b16m3x2 v) => v.BitCast<b16m3x2, b16m3x2>();
}

#endregion // b16m3x2

#region b16m3x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half3x3 asf([This] b16m3x3 v) => v.BitCast<b16m3x3, half3x3>();
    [MethodImpl(256 | 512)]
    public static short3x3 asi([This] b16m3x3 v) => v.BitCast<b16m3x3, short3x3>();
    [MethodImpl(256 | 512)]
    public static ushort3x3 asu([This] b16m3x3 v) => v.BitCast<b16m3x3, ushort3x3>();
    [MethodImpl(256 | 512)]
    public static b16m3x3 asb([This] b16m3x3 v) => v.BitCast<b16m3x3, b16m3x3>();
}

#endregion // b16m3x3

#region b16m3x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half3x4 asf([This] b16m3x4 v) => v.BitCast<b16m3x4, half3x4>();
    [MethodImpl(256 | 512)]
    public static short3x4 asi([This] b16m3x4 v) => v.BitCast<b16m3x4, short3x4>();
    [MethodImpl(256 | 512)]
    public static ushort3x4 asu([This] b16m3x4 v) => v.BitCast<b16m3x4, ushort3x4>();
    [MethodImpl(256 | 512)]
    public static b16m3x4 asb([This] b16m3x4 v) => v.BitCast<b16m3x4, b16m3x4>();
}

#endregion // b16m3x4

#region b16m4x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half4x2 asf([This] b16m4x2 v) => v.BitCast<b16m4x2, half4x2>();
    [MethodImpl(256 | 512)]
    public static short4x2 asi([This] b16m4x2 v) => v.BitCast<b16m4x2, short4x2>();
    [MethodImpl(256 | 512)]
    public static ushort4x2 asu([This] b16m4x2 v) => v.BitCast<b16m4x2, ushort4x2>();
    [MethodImpl(256 | 512)]
    public static b16m4x2 asb([This] b16m4x2 v) => v.BitCast<b16m4x2, b16m4x2>();
}

#endregion // b16m4x2

#region b16m4x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half4x3 asf([This] b16m4x3 v) => v.BitCast<b16m4x3, half4x3>();
    [MethodImpl(256 | 512)]
    public static short4x3 asi([This] b16m4x3 v) => v.BitCast<b16m4x3, short4x3>();
    [MethodImpl(256 | 512)]
    public static ushort4x3 asu([This] b16m4x3 v) => v.BitCast<b16m4x3, ushort4x3>();
    [MethodImpl(256 | 512)]
    public static b16m4x3 asb([This] b16m4x3 v) => v.BitCast<b16m4x3, b16m4x3>();
}

#endregion // b16m4x3

#region b16m4x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half4x4 asf([This] b16m4x4 v) => v.BitCast<b16m4x4, half4x4>();
    [MethodImpl(256 | 512)]
    public static short4x4 asi([This] b16m4x4 v) => v.BitCast<b16m4x4, short4x4>();
    [MethodImpl(256 | 512)]
    public static ushort4x4 asu([This] b16m4x4 v) => v.BitCast<b16m4x4, ushort4x4>();
    [MethodImpl(256 | 512)]
    public static b16m4x4 asb([This] b16m4x4 v) => v.BitCast<b16m4x4, b16m4x4>();
}

#endregion // b16m4x4

#region b32m2x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float2x2 asf([This] b32m2x2 v) => v.BitCast<b32m2x2, float2x2>();
    [MethodImpl(256 | 512)]
    public static int2x2 asi([This] b32m2x2 v) => v.BitCast<b32m2x2, int2x2>();
    [MethodImpl(256 | 512)]
    public static uint2x2 asu([This] b32m2x2 v) => v.BitCast<b32m2x2, uint2x2>();
    [MethodImpl(256 | 512)]
    public static b32m2x2 asb([This] b32m2x2 v) => v.BitCast<b32m2x2, b32m2x2>();
}

#endregion // b32m2x2

#region b32m2x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float2x3 asf([This] b32m2x3 v) => v.BitCast<b32m2x3, float2x3>();
    [MethodImpl(256 | 512)]
    public static int2x3 asi([This] b32m2x3 v) => v.BitCast<b32m2x3, int2x3>();
    [MethodImpl(256 | 512)]
    public static uint2x3 asu([This] b32m2x3 v) => v.BitCast<b32m2x3, uint2x3>();
    [MethodImpl(256 | 512)]
    public static b32m2x3 asb([This] b32m2x3 v) => v.BitCast<b32m2x3, b32m2x3>();
}

#endregion // b32m2x3

#region b32m2x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float2x4 asf([This] b32m2x4 v) => v.BitCast<b32m2x4, float2x4>();
    [MethodImpl(256 | 512)]
    public static int2x4 asi([This] b32m2x4 v) => v.BitCast<b32m2x4, int2x4>();
    [MethodImpl(256 | 512)]
    public static uint2x4 asu([This] b32m2x4 v) => v.BitCast<b32m2x4, uint2x4>();
    [MethodImpl(256 | 512)]
    public static b32m2x4 asb([This] b32m2x4 v) => v.BitCast<b32m2x4, b32m2x4>();
}

#endregion // b32m2x4

#region b32m3x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float3x2 asf([This] b32m3x2 v) => v.BitCast<b32m3x2, float3x2>();
    [MethodImpl(256 | 512)]
    public static int3x2 asi([This] b32m3x2 v) => v.BitCast<b32m3x2, int3x2>();
    [MethodImpl(256 | 512)]
    public static uint3x2 asu([This] b32m3x2 v) => v.BitCast<b32m3x2, uint3x2>();
    [MethodImpl(256 | 512)]
    public static b32m3x2 asb([This] b32m3x2 v) => v.BitCast<b32m3x2, b32m3x2>();
}

#endregion // b32m3x2

#region b32m3x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float3x3 asf([This] b32m3x3 v) => v.BitCast<b32m3x3, float3x3>();
    [MethodImpl(256 | 512)]
    public static int3x3 asi([This] b32m3x3 v) => v.BitCast<b32m3x3, int3x3>();
    [MethodImpl(256 | 512)]
    public static uint3x3 asu([This] b32m3x3 v) => v.BitCast<b32m3x3, uint3x3>();
    [MethodImpl(256 | 512)]
    public static b32m3x3 asb([This] b32m3x3 v) => v.BitCast<b32m3x3, b32m3x3>();
}

#endregion // b32m3x3

#region b32m3x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float3x4 asf([This] b32m3x4 v) => v.BitCast<b32m3x4, float3x4>();
    [MethodImpl(256 | 512)]
    public static int3x4 asi([This] b32m3x4 v) => v.BitCast<b32m3x4, int3x4>();
    [MethodImpl(256 | 512)]
    public static uint3x4 asu([This] b32m3x4 v) => v.BitCast<b32m3x4, uint3x4>();
    [MethodImpl(256 | 512)]
    public static b32m3x4 asb([This] b32m3x4 v) => v.BitCast<b32m3x4, b32m3x4>();
}

#endregion // b32m3x4

#region b32m4x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float4x2 asf([This] b32m4x2 v) => v.BitCast<b32m4x2, float4x2>();
    [MethodImpl(256 | 512)]
    public static int4x2 asi([This] b32m4x2 v) => v.BitCast<b32m4x2, int4x2>();
    [MethodImpl(256 | 512)]
    public static uint4x2 asu([This] b32m4x2 v) => v.BitCast<b32m4x2, uint4x2>();
    [MethodImpl(256 | 512)]
    public static b32m4x2 asb([This] b32m4x2 v) => v.BitCast<b32m4x2, b32m4x2>();
}

#endregion // b32m4x2

#region b32m4x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float4x3 asf([This] b32m4x3 v) => v.BitCast<b32m4x3, float4x3>();
    [MethodImpl(256 | 512)]
    public static int4x3 asi([This] b32m4x3 v) => v.BitCast<b32m4x3, int4x3>();
    [MethodImpl(256 | 512)]
    public static uint4x3 asu([This] b32m4x3 v) => v.BitCast<b32m4x3, uint4x3>();
    [MethodImpl(256 | 512)]
    public static b32m4x3 asb([This] b32m4x3 v) => v.BitCast<b32m4x3, b32m4x3>();
}

#endregion // b32m4x3

#region b32m4x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float4x4 asf([This] b32m4x4 v) => v.BitCast<b32m4x4, float4x4>();
    [MethodImpl(256 | 512)]
    public static int4x4 asi([This] b32m4x4 v) => v.BitCast<b32m4x4, int4x4>();
    [MethodImpl(256 | 512)]
    public static uint4x4 asu([This] b32m4x4 v) => v.BitCast<b32m4x4, uint4x4>();
    [MethodImpl(256 | 512)]
    public static b32m4x4 asb([This] b32m4x4 v) => v.BitCast<b32m4x4, b32m4x4>();
}

#endregion // b32m4x4

#region b64m2x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double2x2 asf([This] b64m2x2 v) => v.BitCast<b64m2x2, double2x2>();
    [MethodImpl(256 | 512)]
    public static long2x2 asi([This] b64m2x2 v) => v.BitCast<b64m2x2, long2x2>();
    [MethodImpl(256 | 512)]
    public static ulong2x2 asu([This] b64m2x2 v) => v.BitCast<b64m2x2, ulong2x2>();
    [MethodImpl(256 | 512)]
    public static b64m2x2 asb([This] b64m2x2 v) => v.BitCast<b64m2x2, b64m2x2>();
}

#endregion // b64m2x2

#region b64m2x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double2x3 asf([This] b64m2x3 v) => v.BitCast<b64m2x3, double2x3>();
    [MethodImpl(256 | 512)]
    public static long2x3 asi([This] b64m2x3 v) => v.BitCast<b64m2x3, long2x3>();
    [MethodImpl(256 | 512)]
    public static ulong2x3 asu([This] b64m2x3 v) => v.BitCast<b64m2x3, ulong2x3>();
    [MethodImpl(256 | 512)]
    public static b64m2x3 asb([This] b64m2x3 v) => v.BitCast<b64m2x3, b64m2x3>();
}

#endregion // b64m2x3

#region b64m2x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double2x4 asf([This] b64m2x4 v) => v.BitCast<b64m2x4, double2x4>();
    [MethodImpl(256 | 512)]
    public static long2x4 asi([This] b64m2x4 v) => v.BitCast<b64m2x4, long2x4>();
    [MethodImpl(256 | 512)]
    public static ulong2x4 asu([This] b64m2x4 v) => v.BitCast<b64m2x4, ulong2x4>();
    [MethodImpl(256 | 512)]
    public static b64m2x4 asb([This] b64m2x4 v) => v.BitCast<b64m2x4, b64m2x4>();
}

#endregion // b64m2x4

#region b64m3x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double3x2 asf([This] b64m3x2 v) => v.BitCast<b64m3x2, double3x2>();
    [MethodImpl(256 | 512)]
    public static long3x2 asi([This] b64m3x2 v) => v.BitCast<b64m3x2, long3x2>();
    [MethodImpl(256 | 512)]
    public static ulong3x2 asu([This] b64m3x2 v) => v.BitCast<b64m3x2, ulong3x2>();
    [MethodImpl(256 | 512)]
    public static b64m3x2 asb([This] b64m3x2 v) => v.BitCast<b64m3x2, b64m3x2>();
}

#endregion // b64m3x2

#region b64m3x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double3x3 asf([This] b64m3x3 v) => v.BitCast<b64m3x3, double3x3>();
    [MethodImpl(256 | 512)]
    public static long3x3 asi([This] b64m3x3 v) => v.BitCast<b64m3x3, long3x3>();
    [MethodImpl(256 | 512)]
    public static ulong3x3 asu([This] b64m3x3 v) => v.BitCast<b64m3x3, ulong3x3>();
    [MethodImpl(256 | 512)]
    public static b64m3x3 asb([This] b64m3x3 v) => v.BitCast<b64m3x3, b64m3x3>();
}

#endregion // b64m3x3

#region b64m3x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double3x4 asf([This] b64m3x4 v) => v.BitCast<b64m3x4, double3x4>();
    [MethodImpl(256 | 512)]
    public static long3x4 asi([This] b64m3x4 v) => v.BitCast<b64m3x4, long3x4>();
    [MethodImpl(256 | 512)]
    public static ulong3x4 asu([This] b64m3x4 v) => v.BitCast<b64m3x4, ulong3x4>();
    [MethodImpl(256 | 512)]
    public static b64m3x4 asb([This] b64m3x4 v) => v.BitCast<b64m3x4, b64m3x4>();
}

#endregion // b64m3x4

#region b64m4x2

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double4x2 asf([This] b64m4x2 v) => v.BitCast<b64m4x2, double4x2>();
    [MethodImpl(256 | 512)]
    public static long4x2 asi([This] b64m4x2 v) => v.BitCast<b64m4x2, long4x2>();
    [MethodImpl(256 | 512)]
    public static ulong4x2 asu([This] b64m4x2 v) => v.BitCast<b64m4x2, ulong4x2>();
    [MethodImpl(256 | 512)]
    public static b64m4x2 asb([This] b64m4x2 v) => v.BitCast<b64m4x2, b64m4x2>();
}

#endregion // b64m4x2

#region b64m4x3

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double4x3 asf([This] b64m4x3 v) => v.BitCast<b64m4x3, double4x3>();
    [MethodImpl(256 | 512)]
    public static long4x3 asi([This] b64m4x3 v) => v.BitCast<b64m4x3, long4x3>();
    [MethodImpl(256 | 512)]
    public static ulong4x3 asu([This] b64m4x3 v) => v.BitCast<b64m4x3, ulong4x3>();
    [MethodImpl(256 | 512)]
    public static b64m4x3 asb([This] b64m4x3 v) => v.BitCast<b64m4x3, b64m4x3>();
}

#endregion // b64m4x3

#region b64m4x4

[Ex]
public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double4x4 asf([This] b64m4x4 v) => v.BitCast<b64m4x4, double4x4>();
    [MethodImpl(256 | 512)]
    public static long4x4 asi([This] b64m4x4 v) => v.BitCast<b64m4x4, long4x4>();
    [MethodImpl(256 | 512)]
    public static ulong4x4 asu([This] b64m4x4 v) => v.BitCast<b64m4x4, ulong4x4>();
    [MethodImpl(256 | 512)]
    public static b64m4x4 asb([This] b64m4x4 v) => v.BitCast<b64m4x4, b64m4x4>();
}

#endregion // b64m4x4
