<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Coplt.Mathematics</RootNamespace>
        <AssemblyName>Coplt.Mathematics</AssemblyName>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Version>1.0.0-preview.0</Version>
        <Description>HLSL-style linear algebra math library with full simd support</Description>
        <PackageProjectUrl>https://github.com/coplt/Coplt.Mathematics</PackageProjectUrl>
        <RepositoryUrl>https://github.com/coplt/Coplt.Mathematics</RepositoryUrl>
        <PackageReadmeFile>Readme.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <NoWarn>CS1591</NoWarn>
    </PropertyGroup>
    
    <ItemGroup>
        <None Include="..\Readme.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
        <None Include="..\LICENSE.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>
    
    <ItemGroup>
      <Folder Include="Algebras\" />
    </ItemGroup>

</Project>
