global using System;
global using System.Numerics;
global using System.Runtime.Intrinsics;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Diagnostics.CodeAnalysis;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using Coplt.Mathematics.Simd;
global using Coplt.Mathematics.Json;
global using Coplt.Shader;
global using static Coplt.Mathematics.FormatUtils;
global using static Coplt.Mathematics.math;
global using static Coplt.Mathematics.ctor;
global using half = System.Half;
global using b16v = Coplt.Mathematics.b16;
global using b32v = Coplt.Mathematics.b32;
global using b64v = Coplt.Mathematics.b64;
global using f16 = System.Half;
global using f32 = float;
global using f64 = double;
global using i8 = sbyte;
global using u8 = byte;
global using i16 = short;
global using u16 = ushort;
global using i32 = int;
global using u32 = uint;
global using i64 = long;
global using u64 = ulong;
