<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
        <LangVersion>13</LangVersion>
        <RazorLangVersion>3.0</RazorLangVersion>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>

        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <IsRoslynComponent>true</IsRoslynComponent>
        <NoWarn>CS9113</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components" Version="3.1.32" />
        <PackageReference Include="Microsoft.AspNetCore.Razor.Runtime" Version="2.2.0" />
        <PackageReference Include="Coplt.RoslynUtilities" Version="0.4.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0" />
        <PackageReference Include="PolySharp" Version="1.15.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    
    <ItemGroup>
        <RazorComponent Include="../Coplt.Mathematics/**/*.razor">
            <Link>Templates\%(RecursiveDir)%(FileName)%(Extension)</Link>
            <TargetPath>Templates\%(RecursiveDir)%(FileName)%(Extension)</TargetPath>
        </RazorComponent>
    </ItemGroup>

</Project>
