using System;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Coplt.Analyzers.Generators;

/// <summary>
/// Generates the vector structs described by <see cref="Typ"/>.
/// </summary>
[Generator]
public class VectorGenerator : IIncrementalGenerator
{
    public const string VecNamespace = "Coplt.Experimental.Mathematics";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            foreach (var typ in Typ.Typs)
            {
                // IVector requires Two and the shift operators, which have no meaning for bool masks
                if (typ.bol) continue;

                for (var size = 2; size <= 4; size++)
                {
                    ctx.AddSource(
                        $"{VecNamespace}.{typ.name}{size}.g.cs",
                        SourceText.From(Gen(typ, size), Encoding.UTF8));
                }
            }
        });
    }

    private static string Gen(Typ typ, int size)
    {
        var type = $"{typ.name}{size}";
        var scalar = typ.compType;
        var byteSize = typ.size * (size == 3 ? 4 : size);
        var bitSize = 8 * byteSize;
        var simd = typ.simd;
        var vecName = $"Vector{bitSize}";
        var vecType = $"{vecName}<{typ.simdComp}>";
        var cast = typ.shuffleCast;
        var attr = "[MethodImpl(256 | 512)]";
        var attrCpu = "[MethodImpl(256 | 512), CpuOnly]";

        var comp = new string[size];
        for (var i = 0; i < size; i++) comp[i] = Typ.xyzw[i];

        string Getter(int i) => simd ? $"vector.GetElement({i})" : $"_{comp[i]}";
        string Setter(int i) => simd ? $"vector = vector.WithElement({i}, value);" : $"_{comp[i]} = value;";

        string Join(Func<int, string> f, string sep = ", ")
        {
            var b = new StringBuilder();
            for (var i = 0; i < size; i++)
            {
                if (i != 0) b.Append(sep);
                b.Append(f(i));
            }
            return b.ToString();
        }

        string Create(params string[] values)
        {
            if (bitSize == 64) return $"{vecName}.Create({values[0]}, {values[1]})";
            if (values.Length == 3) return $"{vecName}.Create({values[0]}, {values[1]}, {values[2]}, default)";
            var b = new StringBuilder($"{vecName}.Create(");
            for (var i = 0; i < values.Length; i++)
            {
                if (i != 0) b.Append(", ");
                b.Append(values[i]);
            }
            b.Append(')');
            return b.ToString();
        }

        string Broadcast(string first) => size == 3
            ? $"{vecName}.Create({first}, value, value, default)"
            : $"{vecName}.Create({first})";

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Runtime.Intrinsics;");
        sb.AppendLine("using Coplt.Mathematics;");
        sb.AppendLine("using Coplt.Mathematics.Generics;");
        sb.AppendLine("using Coplt.Shader;");
        sb.AppendLine();
        sb.AppendLine($"namespace {VecNamespace};");
        sb.AppendLine();
        sb.AppendLine("[Serializable]");
        sb.AppendLine($"public partial struct {type} : IVector<{type}, {scalar}>");
        sb.AppendLine("{");

        #region Meta

        sb.AppendLine();
        sb.AppendLine("    #region Meta");
        sb.AppendLine();
        sb.AppendLine("    public static bool IsSimdAccelerated");
        sb.AppendLine("    {");
        sb.AppendLine($"        {attr}");
        sb.AppendLine($"        get => {(simd ? "true" : "false")};");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static int Length");
        sb.AppendLine("    {");
        sb.AppendLine($"        {attr}");
        sb.AppendLine($"        get => {size};");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static int SizeByte");
        sb.AppendLine("    {");
        sb.AppendLine($"        {attr}");
        sb.AppendLine($"        get => {byteSize};");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static int SizeBit");
        sb.AppendLine("    {");
        sb.AppendLine($"        {attr}");
        sb.AppendLine($"        get => {bitSize};");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    #endregion");

        #endregion

        #region Constants

        sb.AppendLine();
        sb.AppendLine("    #region Constants");
        sb.AppendLine();
        sb.AppendLine($"    public static {type} Zero");
        sb.AppendLine("    {");
        sb.AppendLine($"        {attr}");
        sb.AppendLine("        get => default;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static {type} One");
        sb.AppendLine("    {");
        sb.AppendLine($"        {attr}");
        sb.AppendLine($"        get => new({typ.one});");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static {type} Two");
        sb.AppendLine("    {");
        sb.AppendLine($"        {attr}");
        sb.AppendLine($"        get => new(({scalar})({typ.two}));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    #endregion");

        #endregion

        #region fields

        sb.AppendLine();
        sb.AppendLine("    #region fields");
        sb.AppendLine();
        if (simd)
        {
            sb.AppendLine($"    internal {vecType} vector;");
        }
        else
        {
            for (var i = 0; i < size; i++) sb.AppendLine($"    private {scalar} _{comp[i]};");
            if (size == 3) sb.AppendLine($"    private {scalar} _align;");
        }
        sb.AppendLine();
        for (var i = 0; i < size; i++)
        {
            sb.AppendLine($"    public {scalar} {comp[i]}");
            sb.AppendLine("    {");
            sb.AppendLine($"        {attr}");
            sb.AppendLine($"        readonly get => {Getter(i)};");
            sb.AppendLine($"        {attr}");
            sb.AppendLine($"        set => {Setter(i)}");
            sb.AppendLine("    }");
        }
        for (var i = 0; i < size; i++)
        {
            var xyzw = comp[i];
            var rgba = Typ.rgba[i];
            sb.AppendLine($"    public {scalar} {rgba}");
            sb.AppendLine("    {");
            sb.AppendLine($"        {attr}");
            sb.AppendLine($"        readonly get => {xyzw};");
            sb.AppendLine($"        {attr}");
            sb.AppendLine($"        set => {xyzw} = value;");
            sb.AppendLine("    }");
        }
        sb.AppendLine();
        sb.AppendLine("    #endregion");

        #endregion

        #region ctors

        sb.AppendLine();
        sb.AppendLine("    #region ctors");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public {type}({Join(i => $"{scalar} {comp[i]}")})");
        sb.AppendLine("    {");
        if (simd) sb.AppendLine($"        vector = {Create(comp)};");
        else for (var i = 0; i < size; i++) sb.AppendLine($"        this.{comp[i]} = {comp[i]};");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public {type}(({Join(i => $"{scalar} {comp[i]}")}) tuple) : this({Join(i => $"tuple.{comp[i]}")}) {{ }}");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public static implicit operator {type}(({Join(i => $"{scalar} {comp[i]}")}) tuple) => new(tuple);");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public static implicit operator {type}({scalar} value) => new(value);");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public {type}({scalar} value)");
        sb.AppendLine("    {");
        if (simd) sb.AppendLine($"        vector = {Broadcast($"{cast}value")};");
        else for (var i = 0; i < size; i++) sb.AppendLine($"        {comp[i]} = value;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public static {type} Broadcast({scalar} value) => new(value);");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public static {type} Scalar({scalar} value) => new(value, new is_scalar());");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    internal {type}({scalar} value, is_scalar _)");
        sb.AppendLine("    {");
        if (simd) sb.AppendLine($"        vector = {vecName}.CreateScalar({cast}value);");
        else sb.AppendLine($"        this.{comp[0]} = value;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    {attrCpu}");
        sb.AppendLine($"    public static {type} Load(ReadOnlySpan<{scalar}> span) => new(span);");
        sb.AppendLine();
        sb.AppendLine($"    {attrCpu}");
        sb.AppendLine($"    public {type}(ReadOnlySpan<{scalar}> span)");
        sb.AppendLine("    {");
        if (simd)
        {
            for (var i = 0; i < size; i++) sb.AppendLine($"        var {comp[i]} = span[{i}];");
            sb.AppendLine($"        vector = {Create(comp)};");
        }
        else
        {
            for (var i = 0; i < size; i++) sb.AppendLine($"        this.{comp[i]} = span[{i}];");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    {attrCpu}");
        sb.AppendLine($"    public static unsafe {type} Load({scalar}* ptr) => new(ptr);");
        sb.AppendLine();
        sb.AppendLine($"    {attrCpu}");
        sb.AppendLine($"    public unsafe {type}({scalar}* ptr)");
        sb.AppendLine("    {");
        if (simd)
        {
            for (var i = 0; i < size; i++) sb.AppendLine($"        var {comp[i]} = ptr[{i}];");
            sb.AppendLine($"        vector = {Create(comp)};");
        }
        else
        {
            for (var i = 0; i < size; i++) sb.AppendLine($"        this.{comp[i]} = ptr[{i}];");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    #endregion");

        #endregion

        #region deconstruct

        sb.AppendLine();
        sb.AppendLine("    #region deconstruct");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public readonly void Deconstruct({Join(i => $"out {scalar} {comp[i]}")})");
        sb.AppendLine("    {");
        for (var i = 0; i < size; i++) sb.AppendLine($"        {comp[i]} = this.{comp[i]};");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    #endregion");

        #endregion

        #region index

        sb.AppendLine();
        sb.AppendLine("    #region index");
        sb.AppendLine();
        sb.AppendLine($"    public {scalar} this[int i]");
        sb.AppendLine("    {");
        sb.AppendLine($"        {attr}");
        sb.AppendLine("        readonly get => i switch");
        sb.AppendLine("        {");
        for (var i = 0; i < size; i++) sb.AppendLine($"            {i} => {comp[i]},");
        sb.AppendLine("            _ => throw new IndexOutOfRangeException(nameof(i)),");
        sb.AppendLine("        };");
        sb.AppendLine($"        {attr}");
        sb.AppendLine("        set");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (i)");
        sb.AppendLine("            {");
        for (var i = 0; i < size; i++)
        {
            sb.AppendLine($"                case {i}:");
            sb.AppendLine($"                    {comp[i]} = value;");
            sb.AppendLine("                    break;");
        }
        sb.AppendLine("                default:");
        sb.AppendLine("                    throw new IndexOutOfRangeException(nameof(i));");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    #endregion");

        #endregion

        #region ops

        sb.AppendLine();
        sb.AppendLine("    #region ops");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine("    public readonly override int GetHashCode() => HashCode.Combine(" +
                      Join(i => comp[i]) + ");");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public readonly override bool Equals(object? obj) => obj is {type} other && Equals(other);");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public readonly bool Equals({type} other) => " +
                      Join(i => $"{comp[i]} == other.{comp[i]}", " && ") + ";");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine("    public readonly int CompareTo(object? obj)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (ReferenceEquals(null, obj)) return 1;");
        sb.AppendLine($"        return obj is {type} other ? CompareTo(other) : throw new ArgumentException($\"Object must be of type {{nameof({type})}}\");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public readonly int CompareTo({type} other)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if ({Join(i => $"{comp[i]} < other.{comp[i]}", " || ")}) return -1;");
        sb.AppendLine($"        if ({Join(i => $"{comp[i]} > other.{comp[i]}", " || ")}) return 1;");
        sb.AppendLine("        return 0;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public static bool operator ==({type} left, {type} right) => left.Equals(right);");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public static bool operator !=({type} left, {type} right) => !left.Equals(right);");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public static bool operator <({type} left, {type} right) => " +
                      Join(i => $"left.{comp[i]} < right.{comp[i]}", " && ") + ";");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public static bool operator >({type} left, {type} right) => " +
                      Join(i => $"left.{comp[i]} > right.{comp[i]}", " && ") + ";");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public static bool operator <=({type} left, {type} right) => " +
                      Join(i => $"left.{comp[i]} <= right.{comp[i]}", " && ") + ";");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public static bool operator >=({type} left, {type} right) => " +
                      Join(i => $"left.{comp[i]} >= right.{comp[i]}", " && ") + ";");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public static {type} operator ~({type} a) => new(" + Join(i => $"a.{comp[i]}.BitNot()") + ");");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public static {type} operator &({type} a, {type} b) => new(" +
                      Join(i => $"a.{comp[i]}.BitAnd(b.{comp[i]})") + ");");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public static {type} operator |({type} a, {type} b) => new(" +
                      Join(i => $"a.{comp[i]}.BitOr(b.{comp[i]})") + ");");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public static {type} operator ^({type} a, {type} b) => new(" +
                      Join(i => $"a.{comp[i]}.BitXor(b.{comp[i]})") + ");");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public static {type} operator <<({type} a, int b) => new(" +
                      Join(i => $"a.{comp[i]}.BitShiftLeft(b)") + ");");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public static {type} operator >>({type} a, int b) => new(" +
                      Join(i => $"a.{comp[i]}.BitShiftRight(b)") + ");");
        sb.AppendLine();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public static {type} operator >>>({type} a, int b) => new(" +
                      Join(i => $"a.{comp[i]}.BitShiftRightUnsigned(b)") + ");");
        sb.AppendLine();
        sb.AppendLine("    #endregion");

        #endregion

        sb.AppendLine("}");

        return sb.ToString();
    }
}
