using System;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Coplt.Analyzers.Generators;

/// <summary>
/// Generates the vector structs described by <see cref="Typ"/>.
/// </summary>
[Generator]
public class VectorGenerator : IIncrementalGenerator
{
    public const string VecNamespace = "Coplt.Experimental.Mathematics";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            foreach (var typ in Typ.Typs)
            {
                for (var size = 2; size <= 4; size++)
                {
                    ctx.AddSource(
                        $"{VecNamespace}.{typ.name}{size}.g.cs",
                        SourceText.From(Gen(typ, size), Encoding.UTF8));
                }
            }
        });
    }

    private static string AsMethod(string simdComp) => simdComp switch
    {
        "float" => "AsSingle",
        "double" => "AsDouble",
        "int" => "AsInt32",
        "uint" => "AsUInt32",
        "long" => "AsInt64",
        "ulong" => "AsUInt64",
        _ => throw new InvalidOperationException($"unknown simd comp {simdComp}"),
    };

    private static string Gen(Typ typ, int size)
    {
        var type = $"{typ.name}{size}";
        var scalar = typ.compType;
        var byteSize = typ.size * (size == 3 ? 4 : size);
        var bitSize = 8 * byteSize;
        var bol = typ.bol;
        var iface = bol ? "IBoolVector" : "INumberVector";
        var boolType = $"b{typ.size * 8}v{size}";
        var simd = typ.simd;
        var vecName = $"Vector{bitSize}";
        var vecType = $"{vecName}<{typ.simdComp}>";
        var cast = typ.shuffleCast;
        var attr = "[MethodImpl(256)]";
        var attrCpu = "[MethodImpl(256), CpuOnly]";

        var comp = new string[size];
        for (var i = 0; i < size; i++) comp[i] = Typ.xyzw[i];

        string Getter(int i) => simd ? $"vector.GetElement({i})" : $"_{comp[i]}";
        string Setter(int i) => simd ? $"vector = vector.WithElement({i}, value);" : $"_{comp[i]} = value;";

        string Join(Func<int, string> f, string sep = ", ")
        {
            var b = new StringBuilder();
            for (var i = 0; i < size; i++)
            {
                if (i != 0) b.Append(sep);
                b.Append(f(i));
            }
            return b.ToString();
        }

        string Create(params string[] values)
        {
            if (bitSize == 64) return $"{vecName}.Create({values[0]}, {values[1]})";
            if (values.Length == 3) return $"{vecName}.Create({values[0]}, {values[1]}, {values[2]}, default)";
            var b = new StringBuilder($"{vecName}.Create(");
            for (var i = 0; i < values.Length; i++)
            {
                if (i != 0) b.Append(", ");
                b.Append(values[i]);
            }
            b.Append(')');
            return b.ToString();
        }

        string Broadcast(string first) => size == 3
            ? $"{vecName}.Create({first}, value, value, default)"
            : $"{vecName}.Create({first})";

        // the mask that keeps the padding lane of a 3 component vector at zero
        var mask = !simd || size != 3
            ? null
            : typ.size == 4
                ? $"{vecName}.Create(-1, -1, -1, 0).{AsMethod(typ.simdComp)}()"
                : $"{vecName}.Create(-1L, -1L, -1L, 0L).{AsMethod(typ.simdComp)}()";
        // the int type that has the same width as the components, the comparison masks use it
        var maskAs = typ.size == 4 ? "AsUInt32" : "AsUInt64";
        // bool components are wrappers, the span/pointer has to be reinterpreted
        var spanLoad = scalar == typ.simdComp
            ? "LoadUnsafe(in MemoryMarshal.GetReference(span))"
            : $"LoadUnsafe(in MemoryMarshal.Cast<{scalar}, {typ.simdComp}>(span)[0])";
        var ptrLoad = scalar == typ.simdComp
            ? "Load(ptr)"
            : $"Load(({typ.simdComp}*)ptr)";

        var sb = new StringBuilder();

        void Doc(string text) => sb.AppendLine($"    /// <summary>{text}</summary>");
        void DocParam(string name, string text) => sb.AppendLine($"    /// <param name=\"{name}\">{text}</param>");
        // the members that implement one of the vector interfaces inherit the documentation from it
        void InheritDoc() => sb.AppendLine("    /// <inheritdoc/>");

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using System.Runtime.Intrinsics;");
        sb.AppendLine("using Coplt.Mathematics;");
        sb.AppendLine("using Coplt.Mathematics.Generics;");
        sb.AppendLine("using Coplt.Shader;");
        sb.AppendLine();
        sb.AppendLine($"namespace {VecNamespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// {type} is a vector of {size} {scalar} components" +
                      (size == 3 ? ", it is padded to 4 components" : "") +
                      (simd ? ", it is backed by a hardware accelerated simd type" : ""));
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[Serializable]");
        sb.AppendLine($"public partial struct {type} :");
        sb.AppendLine($"    {iface}<{type}, {scalar}>,");
        sb.AppendLine($"    IEqualityOperators<{type}, {type}, {boolType}>,");
        sb.AppendLine($"    IComparisonOperators<{type}, {type}, {boolType}>");
        sb.AppendLine("{");

        #region Meta

        sb.AppendLine();
        sb.AppendLine("    #region Meta");
        sb.AppendLine();
        InheritDoc();
        sb.AppendLine("    public static bool IsSimdAccelerated");
        sb.AppendLine("    {");
        sb.AppendLine($"        {attr}");
        sb.AppendLine($"        get => {(simd ? "true" : "false")};");
        sb.AppendLine("    }");
        sb.AppendLine();
        InheritDoc();
        sb.AppendLine("    public static int Length");
        sb.AppendLine("    {");
        sb.AppendLine($"        {attr}");
        sb.AppendLine($"        get => {size};");
        sb.AppendLine("    }");
        sb.AppendLine();
        InheritDoc();
        sb.AppendLine("    public static int SizeByte");
        sb.AppendLine("    {");
        sb.AppendLine($"        {attr}");
        sb.AppendLine($"        get => {byteSize};");
        sb.AppendLine("    }");
        sb.AppendLine();
        InheritDoc();
        sb.AppendLine("    public static int SizeBit");
        sb.AppendLine("    {");
        sb.AppendLine($"        {attr}");
        sb.AppendLine($"        get => {bitSize};");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    #endregion");

        #endregion

        #region Constants

        sb.AppendLine();
        sb.AppendLine("    #region Constants");
        sb.AppendLine();
        if (bol)
        {
            InheritDoc();
            sb.AppendLine($"    public static {type} True");
            sb.AppendLine("    {");
            sb.AppendLine($"        {attr}");
            sb.AppendLine($"        get => new({typ.one});");
            sb.AppendLine("    }");
            sb.AppendLine();
            InheritDoc();
            sb.AppendLine($"    public static {type} False");
            sb.AppendLine("    {");
            sb.AppendLine($"        {attr}");
            sb.AppendLine("        get => default;");
            sb.AppendLine("    }");
        }
        else
        {
            InheritDoc();
            sb.AppendLine($"    public static {type} Zero");
            sb.AppendLine("    {");
            sb.AppendLine($"        {attr}");
            sb.AppendLine("        get => default;");
            sb.AppendLine("    }");
            sb.AppendLine();
            InheritDoc();
            sb.AppendLine($"    public static {type} One");
            sb.AppendLine("    {");
            sb.AppendLine($"        {attr}");
            sb.AppendLine($"        get => new({typ.one});");
            sb.AppendLine("    }");
            sb.AppendLine();
            InheritDoc();
            sb.AppendLine($"    public static {type} Two");
            sb.AppendLine("    {");
            sb.AppendLine($"        {attr}");
            sb.AppendLine($"        get => new(({scalar})({typ.two}));");
            sb.AppendLine("    }");
            sb.AppendLine();
            InheritDoc();
            sb.AppendLine($"    public static {scalar} ScalarTwo");
            sb.AppendLine("    {");
            sb.AppendLine($"        {attr}");
            sb.AppendLine($"        get => ({scalar})({typ.two});");
            sb.AppendLine("    }");
            sb.AppendLine();
            InheritDoc();
            sb.AppendLine($"    public static {scalar} ScalarZero");
            sb.AppendLine("    {");
            sb.AppendLine($"        {attr}");
            sb.AppendLine("        get => default;");
            sb.AppendLine("    }");
            sb.AppendLine();
            InheritDoc();
            sb.AppendLine($"    public static {scalar} ScalarOne");
            sb.AppendLine("    {");
            sb.AppendLine($"        {attr}");
            sb.AppendLine($"        get => {typ.one};");
            sb.AppendLine("    }");
        }
        sb.AppendLine();
        sb.AppendLine("    #endregion");

        #endregion

        #region fields

        sb.AppendLine();
        sb.AppendLine("    #region fields");
        sb.AppendLine();
        if (simd)
        {
            Doc("The raw simd value of the vector, writing it directly bypasses the padding lane mask of a 3 component vector");
            sb.AppendLine($"    public {vecType} vector;");
        }
        else
        {
            for (var i = 0; i < size; i++) sb.AppendLine($"    private {scalar} _{comp[i]};");
            if (size == 3) sb.AppendLine($"    private {scalar} _align;");
        }
        sb.AppendLine();
        for (var i = 0; i < size; i++)
        {
            Doc($"The {comp[i]} component");
            sb.AppendLine($"    public {scalar} {comp[i]}");
            sb.AppendLine("    {");
            sb.AppendLine($"        {attr}");
            sb.AppendLine($"        readonly get => {Getter(i)};");
            sb.AppendLine($"        {attr}");
            sb.AppendLine($"        set => {Setter(i)}");
            sb.AppendLine("    }");
        }
        var colorName = new[] { "red", "green", "blue", "alpha" };
        for (var i = 0; i < size; i++)
        {
            var xyzw = comp[i];
            var rgba = Typ.rgba[i];
            Doc($"The {colorName[i]} component, it is the same as <c>{xyzw}</c>");
            sb.AppendLine($"    public {scalar} {rgba}");
            sb.AppendLine("    {");
            sb.AppendLine($"        {attr}");
            sb.AppendLine($"        readonly get => {xyzw};");
            sb.AppendLine($"        {attr}");
            sb.AppendLine($"        set => {xyzw} = value;");
            sb.AppendLine("    }");
        }
        sb.AppendLine();
        sb.AppendLine("    #endregion");

        #endregion

        #region ctors

        sb.AppendLine();
        sb.AppendLine("    #region ctors");
        sb.AppendLine();
        if (simd)
        {
            Doc(mask == null
                ? "Creates a vector from a raw simd value"
                : "Creates a vector from a raw simd value, the padding lane of a 3 component vector is set to zero");
            DocParam("vector", "The raw simd value");
            sb.AppendLine($"    {attr}");
            sb.AppendLine($"    public {type}({vecType} vector) => this.vector = " +
                          (mask == null ? "vector;" : $"vector & {mask};"));
            sb.AppendLine();
        }
        Doc("Creates a vector from its components");
        for (var i = 0; i < size; i++) DocParam(comp[i], $"The {comp[i]} component");
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public {type}({Join(i => $"{scalar} {comp[i]}")})");
        sb.AppendLine("    {");
        if (simd) sb.AppendLine($"        vector = {Create(comp)};");
        else for (var i = 0; i < size; i++) sb.AppendLine($"        this.{comp[i]} = {comp[i]};");
        sb.AppendLine("    }");
        sb.AppendLine();
        Doc("Creates a vector from a tuple of its components");
        DocParam("tuple", "The tuple of the components");
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public {type}(({Join(i => $"{scalar} {comp[i]}")}) tuple) : this({Join(i => $"tuple.{comp[i]}")}) {{ }}");
        sb.AppendLine();
        Doc("Converts a tuple of the components to a vector");
        DocParam("tuple", "The tuple of the components");
        sb.AppendLine("    /// <returns>The vector</returns>");
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public static implicit operator {type}(({Join(i => $"{scalar} {comp[i]}")}) tuple) => new(tuple);");
        sb.AppendLine();
        Doc("Converts a scalar to a broadcast vector");
        DocParam("value", "The value of every component");
        sb.AppendLine("    /// <returns>The broadcast vector</returns>");
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public static implicit operator {type}({scalar} value) => new(value);");
        sb.AppendLine();
        Doc("Creates a vector with every component set to <paramref name=\"value\"/>");
        DocParam("value", "The value of every component");
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public {type}({scalar} value)");
        sb.AppendLine("    {");
        if (simd) sb.AppendLine($"        vector = {Broadcast($"{cast}value")};");
        else for (var i = 0; i < size; i++) sb.AppendLine($"        {comp[i]} = value;");
        sb.AppendLine("    }");
        sb.AppendLine();
        Doc("Creates a vector with every component set to <paramref name=\"value\"/>");
        DocParam("value", "The value of every component");
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public static {type} Broadcast({scalar} value) => new(value);");
        sb.AppendLine();
        Doc($"Creates a vector with only the {comp[0]} component set to <paramref name=\"value\"/>, the other components are zero");
        DocParam("value", $"The value of the {comp[0]} component");
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public static {type} Scalar({scalar} value) => new() {{ " +
                      (simd ? $"vector = {vecName}.CreateScalar({cast}value)" : $"{comp[0]} = value") + " };");
        sb.AppendLine();
        InheritDoc();
        sb.AppendLine($"    {attrCpu}");
        sb.AppendLine($"    public static {type} Load(ReadOnlySpan<{scalar}> span) => new(span);");
        sb.AppendLine();
        Doc(simd
            ? "Creates a vector from the beginning of <paramref name=\"span\"/>, it reads a whole simd register, so the span has to be at least as long as the padded vector"
            : "Creates a vector from the beginning of <paramref name=\"span\"/>");
        DocParam("span", "The span to load from");
        sb.AppendLine($"    {attrCpu}");
        if (simd)
        {
            // routed through the vector constructor so the padding lane mask is applied
            sb.AppendLine($"    public {type}(ReadOnlySpan<{scalar}> span) : this({vecName}.{spanLoad}) {{ }}");
        }
        else
        {
            sb.AppendLine($"    public {type}(ReadOnlySpan<{scalar}> span)");
            sb.AppendLine("    {");
            for (var i = 0; i < size; i++) sb.AppendLine($"        this.{comp[i]} = span[{i}];");
            sb.AppendLine("    }");
        }
        sb.AppendLine();
        InheritDoc();
        sb.AppendLine($"    {attrCpu}");
        sb.AppendLine($"    public static unsafe {type} Load({scalar}* ptr) => new(ptr);");
        sb.AppendLine();
        Doc(simd
            ? "Creates a vector from <paramref name=\"ptr\"/>, it reads a whole simd register, so the pointer has to point to at least as many components as the padded vector"
            : "Creates a vector from <paramref name=\"ptr\"/>");
        DocParam("ptr", "The pointer to load from");
        sb.AppendLine($"    {attrCpu}");
        if (simd)
        {
            sb.AppendLine($"    public unsafe {type}({scalar}* ptr) : this({vecName}.{ptrLoad}) {{ }}");
        }
        else
        {
            sb.AppendLine($"    public unsafe {type}({scalar}* ptr)");
            sb.AppendLine("    {");
            for (var i = 0; i < size; i++) sb.AppendLine($"        this.{comp[i]} = ptr[{i}];");
            sb.AppendLine("    }");
        }
        sb.AppendLine();
        sb.AppendLine("    #endregion");

        #endregion

        #region deconstruct

        sb.AppendLine();
        sb.AppendLine("    #region deconstruct");
        sb.AppendLine();
        Doc("Deconstructs the vector into its components");
        for (var i = 0; i < size; i++) DocParam(comp[i], $"Receives the {comp[i]} component");
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public readonly void Deconstruct({Join(i => $"out {scalar} {comp[i]}")})");
        sb.AppendLine("    {");
        for (var i = 0; i < size; i++) sb.AppendLine($"        {comp[i]} = this.{comp[i]};");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    #endregion");

        #endregion

        #region index

        sb.AppendLine();
        sb.AppendLine("    #region index");
        sb.AppendLine();
        InheritDoc();
        sb.AppendLine($"    public {scalar} this[int i]");
        sb.AppendLine("    {");
        sb.AppendLine($"        {attr}");
        sb.AppendLine("        readonly get => i switch");
        sb.AppendLine("        {");
        for (var i = 0; i < size; i++) sb.AppendLine($"            {i} => {comp[i]},");
        sb.AppendLine("            _ => throw new IndexOutOfRangeException(nameof(i)),");
        sb.AppendLine("        };");
        sb.AppendLine($"        {attr}");
        sb.AppendLine("        set");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (i)");
        sb.AppendLine("            {");
        for (var i = 0; i < size; i++)
        {
            sb.AppendLine($"                case {i}:");
            sb.AppendLine($"                    {comp[i]} = value;");
            sb.AppendLine("                    break;");
        }
        sb.AppendLine("                default:");
        sb.AppendLine("                    throw new IndexOutOfRangeException(nameof(i));");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    #endregion");

        #endregion

        #region ops

        sb.AppendLine();
        sb.AppendLine("    #region ops");
        sb.AppendLine();
        InheritDoc();
        sb.AppendLine($"    {attr}");
        sb.AppendLine("    public readonly override int GetHashCode() => HashCode.Combine(" +
                      Join(i => comp[i]) + ");");
        sb.AppendLine();
        InheritDoc();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public readonly override bool Equals(object? obj) => obj is {type} other && Equals(other);");
        sb.AppendLine();
        // emits the accelerated fast paths, falls back to the scalar expression when no vector is accelerated
        void EmitSimd(string full, string wide, string fallback)
        {
            if (simd)
            {
                sb.AppendLine($"        if ({vecName}.IsHardwareAccelerated)");
                sb.AppendLine($"            return {full};");
                if (bitSize == 64)
                {
                    sb.AppendLine("        if (Vector128.IsHardwareAccelerated)");
                    sb.AppendLine($"            return {wide};");
                }
            }
            sb.AppendLine($"        return {fallback};");
        }

        // emits a comparison operator that returns the bool vector, it is not part of the vector interfaces
        void EmitMaskOp(string op, string vecOp, bool invert, string scalarOp, string doc)
        {
            string MaskExpr(string name, bool to64)
            {
                var args = to64 ? "left.vector.ToVector128(), right.vector.ToVector128()" : "left.vector, right.vector";
                var expr = $"{name}.{vecOp}({args}).{maskAs}()";
                if (invert) expr = $"~{expr}";
                return to64 ? $"Vector128.GetLower({expr})" : expr;
            }

            Doc(doc);
            DocParam("left", "The left vector");
            DocParam("right", "The right vector");
            sb.AppendLine("    /// <returns>A mask with the result of every component</returns>");
            sb.AppendLine($"    {attr}");
            sb.AppendLine($"    public static {boolType} operator {op}({type} left, {type} right)");
            sb.AppendLine("    {");
            if (simd)
            {
                sb.AppendLine($"        if ({vecName}.IsHardwareAccelerated)");
                sb.AppendLine($"            return new({MaskExpr(vecName, false)});");
                if (bitSize == 64)
                {
                    sb.AppendLine("        if (Vector128.IsHardwareAccelerated)");
                    sb.AppendLine($"            return new({MaskExpr("Vector128", true)});");
                }
            }
            sb.AppendLine($"        return new({Join(i => $"left.{comp[i]} {scalarOp} right.{comp[i]}")});");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // emits the bool result of a comparison operator required by IComparisonOperators
        void EmitBoolOp(string op, string vecOp, string scalarOp)
        {
            // the padding lane of a 3 component vector is zero on both sides, an all comparison over the whole
            // vector would be false for it, so the mask is compared against the expected mask instead
            var lessOp = vecOp switch
            {
                "LessThanAll" => "LessThan",
                "GreaterThanAll" => "GreaterThan",
                _ => null,
            };
            var expected = size != 3
                ? $"{vecName}<{(typ.size == 4 ? "uint" : "ulong")}>.AllBitsSet"
                : typ.size == 4
                    ? $"{vecName}.Create(-1, -1, -1, 0).AsUInt32()"
                    : $"{vecName}.Create(-1L, -1L, -1L, 0L).AsUInt64()";

            InheritDoc();
            sb.AppendLine($"    {attr}");
            sb.AppendLine($"    static bool IComparisonOperators<{type}, {type}, bool>.operator {op}({type} left, {type} right)");
            sb.AppendLine("    {");
            if (simd)
            {
                sb.AppendLine($"        if ({vecName}.IsHardwareAccelerated)");
                if (lessOp == null)
                    sb.AppendLine($"            return {vecName}.{vecOp}(left.vector, right.vector);");
                else
                    sb.AppendLine($"            return {vecName}.EqualsAll({vecName}.{lessOp}(left.vector, right.vector).{maskAs}(), {expected});");
                if (bitSize == 64)
                {
                    sb.AppendLine("        if (Vector128.IsHardwareAccelerated)");
                    if (lessOp == null)
                        sb.AppendLine($"            return Vector128.{vecOp}(left.vector.ToVector128(), right.vector.ToVector128());");
                    else
                        // the upper lanes of the widened operands are zero, only the low 64 bits of the mask are meaningful
                        sb.AppendLine($"            return Vector64.EqualsAll(Vector128.GetLower(Vector128.{lessOp}(left.vector.ToVector128(), right.vector.ToVector128()).AsUInt32()), Vector64<uint>.AllBitsSet);");
                }
            }
            sb.AppendLine($"        return {Join(i => $"left.{comp[i]} {scalarOp} right.{comp[i]}", " && ")};");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        InheritDoc();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public readonly bool Equals({type} other)");
        sb.AppendLine("    {");
        EmitSimd(
            $"{vecName}.EqualsAll(vector, other.vector)",
            "Vector128.EqualsAll(vector.ToVector128(), other.vector.ToVector128())",
            Join(i => $"{comp[i]} == other.{comp[i]}", " && "));
        sb.AppendLine("    }");
        sb.AppendLine();
        if (!bol)
        {
            InheritDoc();
            sb.AppendLine($"    {attr}");
            sb.AppendLine("    public readonly int CompareTo(object? obj)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (ReferenceEquals(null, obj)) return 1;");
            sb.AppendLine($"        return obj is {type} other ? CompareTo(other) : throw new ArgumentException($\"Object must be of type {{nameof({type})}}\");");
            sb.AppendLine("    }");
            sb.AppendLine();
            InheritDoc();
            sb.AppendLine($"    {attr}");
            sb.AppendLine($"    public readonly int CompareTo({type} other)");
            sb.AppendLine("    {");
            if (simd)
            {
                sb.AppendLine($"        if ({vecName}.IsHardwareAccelerated)");
                sb.AppendLine("        {");
                sb.AppendLine($"            if ({vecName}.LessThanAny(vector, other.vector)) return -1;");
                sb.AppendLine($"            if ({vecName}.GreaterThanAny(vector, other.vector)) return 1;");
                sb.AppendLine("            return 0;");
                sb.AppendLine("        }");
                if (bitSize == 64)
                {
                    sb.AppendLine("        if (Vector128.IsHardwareAccelerated)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            if (Vector128.LessThanAny(vector.ToVector128(), other.vector.ToVector128())) return -1;");
                    sb.AppendLine("            if (Vector128.GreaterThanAny(vector.ToVector128(), other.vector.ToVector128())) return 1;");
                    sb.AppendLine("            return 0;");
                    sb.AppendLine("        }");
                }
            }
            sb.AppendLine($"        if ({Join(i => $"{comp[i]} < other.{comp[i]}", " || ")}) return -1;");
            sb.AppendLine($"        if ({Join(i => $"{comp[i]} > other.{comp[i]}", " || ")}) return 1;");
            sb.AppendLine("        return 0;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
        EmitMaskOp("==", "Equals", false, "==",
            "Returns a mask that is true where the components of the two vectors are equal");
        EmitMaskOp("!=", "Equals", true, "!=",
            "Returns a mask that is true where the components of the two vectors are not equal");
        EmitMaskOp("<", "LessThan", false, "<",
            "Returns a mask that is true where a component of the left vector is less than the component of the right vector");
        EmitMaskOp(">", "GreaterThan", false, ">",
            "Returns a mask that is true where a component of the left vector is greater than the component of the right vector");
        EmitMaskOp("<=", "LessThanOrEqual", false, "<=",
            "Returns a mask that is true where a component of the left vector is less than or equal to the component of the right vector");
        EmitMaskOp(">=", "GreaterThanOrEqual", false, ">=",
            "Returns a mask that is true where a component of the left vector is greater than or equal to the component of the right vector");
        InheritDoc();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    static bool IEqualityOperators<{type}, {type}, bool>.operator ==({type} left, {type} right) => left.Equals(right);");
        sb.AppendLine();
        InheritDoc();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    static bool IEqualityOperators<{type}, {type}, bool>.operator !=({type} left, {type} right) => !left.Equals(right);");
        sb.AppendLine();
        if (!bol)
        {
            EmitBoolOp("<", "LessThanAll", "<");
            EmitBoolOp(">", "GreaterThanAll", ">");
            EmitBoolOp("<=", "LessThanOrEqualAll", "<=");
            EmitBoolOp(">=", "GreaterThanOrEqualAll", ">=");
        }
        // emits a bitwise operator, the scalar expression is only used when no vector is accelerated
        void EmitBitOp(string op, string rhs, string vecRhs, string wideRhs, string scalarExpr)
        {
            InheritDoc();
            sb.AppendLine($"    {attr}");
            sb.AppendLine($"    public static {type} operator {op}({type} a, {rhs} b)");
            sb.AppendLine("    {");
            if (simd)
            {
                sb.AppendLine($"        if ({vecName}.IsHardwareAccelerated)");
                sb.AppendLine($"            return new(a.vector {op} {vecRhs});");
                if (bitSize == 64)
                {
                    sb.AppendLine("        if (Vector128.IsHardwareAccelerated)");
                    sb.AppendLine($"            return new(Vector128.GetLower(a.vector.ToVector128() {op} {wideRhs}));");
                }
            }
            sb.AppendLine($"        return new({scalarExpr});");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        InheritDoc();
        sb.AppendLine($"    {attr}");
        sb.AppendLine($"    public static {type} operator ~({type} a)");
        sb.AppendLine("    {");
        if (simd)
        {
            sb.AppendLine($"        if ({vecName}.IsHardwareAccelerated)");
            sb.AppendLine("            return new(~a.vector);");
            if (bitSize == 64)
            {
                sb.AppendLine("        if (Vector128.IsHardwareAccelerated)");
                sb.AppendLine("            return new(Vector128.GetLower(~a.vector.ToVector128()));");
            }
        }
        sb.AppendLine($"        return new({Join(i => $"a.{comp[i]}.BitNot()")});");
        sb.AppendLine("    }");
        sb.AppendLine();
        EmitBitOp("&", type, "b.vector", "b.vector.ToVector128()",
            Join(i => $"a.{comp[i]}.BitAnd(b.{comp[i]})"));
        EmitBitOp("|", type, "b.vector", "b.vector.ToVector128()",
            Join(i => $"a.{comp[i]}.BitOr(b.{comp[i]})"));
        EmitBitOp("^", type, "b.vector", "b.vector.ToVector128()",
            Join(i => $"a.{comp[i]}.BitXor(b.{comp[i]})"));
        if (!bol)
        {
            EmitBitOp("<<", "int", "b", "b",
                Join(i => $"a.{comp[i]}.BitShiftLeft(b)"));
            EmitBitOp(">>", "int", "b", "b",
                Join(i => $"a.{comp[i]}.BitShiftRight(b)"));
            EmitBitOp(">>>", "int", "b", "b",
                Join(i => $"a.{comp[i]}.BitShiftRightUnsigned(b)"));
        }
        sb.AppendLine("    #endregion");

        #endregion

        sb.AppendLine("}");

        return sb.ToString();
    }
}
