using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Coplt.Analyzers.Generators;

/// <summary>
/// Generates the interfaces of every shape of matrix, a shape is the number of the rows of a matrix and the
/// number of its columns. A shape has the interface of its own beside the two forms of it: the form that
/// reaches the columns of the matrix through a vector and the form that reaches the components of it by a
/// scalar. Every column and every component of the shape is a member of the form of it, a member is named by
/// the column it reaches, <c>c0</c>, or by the row and the column of the component it reaches, <c>m00</c>.
/// A matrix also implements the interface of the number of its columns, which reaches the columns of it
/// without naming the number of the rows of it. The members are emitted into one file per shape and one file
/// per number of columns.
/// </summary>
[Generator]
public class MatrixShapeGenerator : IIncrementalGenerator
{
    public const string AlgebrasNamespace = "Coplt.Mathematics.Algebras";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            // the columns of a matrix are the value of it, so a caller that does not know the number of the rows
            // of a matrix reaches them through the interface of the number of the columns
            for (var cols = 2; cols <= 4; cols++)
            {
                ctx.AddSource(
                    $"{AlgebrasNamespace}.IMatrixMx{cols}.g.cs",
                    SourceText.From(GenColumns(cols), Encoding.UTF8));
            }

            for (var rows = 2; rows <= 4; rows++)
            {
                for (var cols = 2; cols <= 4; cols++)
                {
                    var shape = $"{rows}x{cols}";
                    ctx.AddSource(
                        $"{AlgebrasNamespace}.IMatrix{shape}.g.cs",
                        SourceText.From(Gen(rows, cols, shape), Encoding.UTF8));
                }
            }
        });
    }

    /// <summary>
    /// Generates the interfaces that name the number of the columns of a matrix but hide the number of its rows.
    /// The vector of a column is a part of the name of every member of them, so a caller that only knows the
    /// number of the columns of a matrix reaches the columns of every matrix that has them. The shape of a
    /// matrix implements the interface of the number of its columns beside the interface of its own shape.
    /// </summary>
    /// <param name="cols">The number of the columns of the matrix</param>
    /// <returns>The interfaces of the number of the columns</returns>
    private static string GenColumns(int cols)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"// A matrix that implements one of the interfaces below has {cols} columns. The number of the rows of");
        sb.AppendLine("// it is the number of the components of the vector of a column, it is not named by them.");
        sb.AppendLine();
        sb.AppendLine($"namespace {AlgebrasNamespace};");
        sb.AppendLine();
        sb.AppendLine($"public interface IMatrixMx{cols}<TSelf> : IMatrix<TSelf>");
        sb.AppendLine($"    where TSelf : unmanaged, IMatrixMx{cols}<TSelf>;");
        sb.AppendLine();
        sb.AppendLine($"public interface IMatrixMx{cols}Vector<TSelf, TVector> : " +
                      $"IMatrixMx{cols}<TSelf>, IMatrixVector<TSelf, TVector>");
        sb.AppendLine($"    where TSelf : unmanaged, IMatrixMx{cols}Vector<TSelf, TVector>");
        sb.AppendLine("    where TVector : unmanaged, IVector<TVector>");
        sb.AppendLine("{");
        EmitColumns(sb, cols);
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Emits the members that reach the columns of a matrix through the vector of a column.
    /// </summary>
    /// <param name="sb">The builder of the file</param>
    /// <param name="cols">The number of the columns of the matrix</param>
    private static void EmitColumns(StringBuilder sb, int cols)
    {
        sb.AppendLine("    #region Create");
        sb.AppendLine();
        sb.AppendLine($"    public static abstract TSelf Create({VectorGenShared.Join(cols, i => $"in TVector c{i}")});");
        sb.AppendLine();
        sb.AppendLine("    #endregion");
        sb.AppendLine();
        sb.AppendLine("    #region Index");
        sb.AppendLine();
        for (var j = 0; j < cols; j++)
        {
            sb.AppendLine($"    public static abstract TVector get_c{j}(in TSelf self);");
            sb.AppendLine($"    public static abstract void set_c{j}(ref TSelf self, in TVector value);");
        }

        sb.AppendLine();
        sb.AppendLine("    #endregion");
    }

    private static string Gen(int rows, int cols, string shape)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {AlgebrasNamespace};");
        sb.AppendLine();
        sb.AppendLine($"public interface IMatrix{shape}<TSelf> : IMatrixMx{cols}<TSelf>");
        sb.AppendLine($"    where TSelf : unmanaged, IMatrix{shape}<TSelf>;");
        sb.AppendLine();

        // the form that reaches the columns of the matrix through the vector of a column, the members of it are
        // the ones of the number of the columns, the shape of the matrix only names the vector of a column
        sb.AppendLine($"public interface IMatrix{shape}Vector<TSelf, TVector> : " +
                      $"IMatrix{shape}<TSelf>, IMatrixMx{cols}Vector<TSelf, TVector>");
        sb.AppendLine($"    where TSelf : unmanaged, IMatrix{shape}Vector<TSelf, TVector>");
        sb.AppendLine("    where TVector : unmanaged, IVector<TVector>;");
        sb.AppendLine();

        // the form that reaches the components of the matrix by the row and the column of a component
        sb.AppendLine($"public interface IMatrix{shape}Scalar<TSelf, TScalar> : " +
                      $"IMatrix{shape}<TSelf>, IMatrixScalar<TSelf, TScalar>");
        sb.AppendLine($"    where TSelf : unmanaged, IMatrix{shape}Scalar<TSelf, TScalar>");
        sb.AppendLine("    where TScalar : unmanaged");
        sb.AppendLine("{");
        sb.AppendLine("    #region Create");
        sb.AppendLine();
        var args = new StringBuilder();
        for (var r = 0; r < rows; r++)
        {
            for (var c = 0; c < cols; c++)
            {
                if (args.Length != 0) args.Append(", ");
                args.Append($"TScalar m{r}{c}");
            }
        }

        sb.AppendLine($"    public static abstract TSelf Create({args});");
        sb.AppendLine();
        sb.AppendLine("    #endregion");
        sb.AppendLine();
        sb.AppendLine("    #region Index");
        sb.AppendLine();
        for (var r = 0; r < rows; r++)
        {
            for (var c = 0; c < cols; c++)
            {
                sb.AppendLine($"    public static abstract TScalar get_m{r}{c}(in TSelf self);");
                sb.AppendLine($"    public static abstract void set_m{r}{c}(ref TSelf self, TScalar value);");
            }
        }

        sb.AppendLine();
        sb.AppendLine("    #endregion");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
