using Coplt.Mathematics;
using static Coplt.Mathematics.math;

namespace Tests.Scalar;

/// <summary>
/// The functions of the scalar types. Every numeric type has the functions of the <c>math</c> class and the
/// members that are called on a value, which are the members of <c>ScalarExtensions</c>, they are generated by
/// the source generator.
/// </summary>
public class TestScalarMath
{
    [Test]
    public void Arithmetic()
    {
        Assert.That(min(3, 5), Is.EqualTo(3));
        Assert.That(max(3, 5), Is.EqualTo(5));
        Assert.That(clamp(7, 1, 5), Is.EqualTo(5));
        Assert.That(clamp(0, 1, 5), Is.EqualTo(1));
        Assert.That(abs(-4), Is.EqualTo(4));
        Assert.That(sign(-4), Is.EqualTo(-1));
        Assert.That(sign(4), Is.EqualTo(1));
        Assert.That(sign(0), Is.EqualTo(0));
        Assert.That(square(3), Is.EqualTo(9));
        Assert.That(dot(3, 4), Is.EqualTo(12));
        Assert.That(fma(2, 3, 4), Is.EqualTo(10));
        Assert.That(fms(2, 3, 4), Is.EqualTo(2));
        Assert.That(fnma(2, 3, 4), Is.EqualTo(-2));
        Assert.That(lerp(0, 10, 1), Is.EqualTo(10));
        Assert.That(unlerp(5, 0, 10), Is.EqualTo(0));
        Assert.That(remap(3, 0, 3, 0, 9), Is.EqualTo(9));
        Assert.That(length_sq(-3), Is.EqualTo(9));
        Assert.That(distance_sq(2, 5), Is.EqualTo(9));
    }

    [Test]
    public void EveryIntegerType()
    {
        Assert.That(min(3u, 5u), Is.EqualTo(3u));
        Assert.That(abs(-4L), Is.EqualTo(4L));
        Assert.That(sign(4ul), Is.EqualTo(1ul));
        Assert.That(square((short)-3), Is.EqualTo((short)9));
        Assert.That(dot((ushort)3, (ushort)4), Is.EqualTo((ushort)12));
        Assert.That(distance_sq((short)2, (short)5), Is.EqualTo((short)9));
        Assert.That(up2pow2((ushort)5), Is.EqualTo((ushort)8));
    }

    [Test]
    public void FloatingPoint()
    {
        Assert.That(ceil(1.2f), Is.EqualTo(2f));
        Assert.That(floor(1.8f), Is.EqualTo(1f));
        Assert.That(round(1.5f), Is.EqualTo(2f));
        Assert.That(trunc(-1.8f), Is.EqualTo(-1f));
        Assert.That(frac(-1.25f), Is.EqualTo(0.75f));
        Assert.That(mod(-1f, 3f), Is.EqualTo(2f));
        // the product of the remainder is fused, so the subtraction of it is exact
        Assert.That(mod(1f, 0.1f), Is.EqualTo(-1.4901161193847656E-08f));
        Assert.That(rcp(4f), Is.EqualTo(0.25f));
        Assert.That(saturate(2f), Is.EqualTo(1f));
        Assert.That(step(2f, 3f), Is.EqualTo(1f));
        Assert.That(step(3f, 2f), Is.EqualTo(0f));
        Assert.That(smoothstep(0f, 1f, 0.5f), Is.EqualTo(0.5f));
        Assert.That(reflect(1f, 1f), Is.EqualTo(-1f));
        Assert.That(project(2f, 1f), Is.EqualTo(2f));
        Assert.That(project_normalized(2f, 1f), Is.EqualTo(2f));
        Assert.That(project_on_plane(2f, 1f), Is.EqualTo(0f));
        Assert.That(project_on_plane_normalized(2f, 1f), Is.EqualTo(0f));
        Assert.That(project_safe(2f, 0f), Is.EqualTo(0f));
        Assert.That(wrap(4f, 0f, 3f), Is.EqualTo(1f));
        Assert.That(wrap(-1f, 0f, 3f), Is.EqualTo(2f));
        Assert.That(length(-3f), Is.EqualTo(3f));
        Assert.That(distance(2f, 5f), Is.EqualTo(3f));
        Assert.That(normalize(2f), Is.EqualTo(1f));
        Assert.That(normalize_safe(0f), Is.EqualTo(0f));
        Assert.That(refract(1f, 1f, 1f), Is.EqualTo(-1f));
        Assert.That(radians(180f), Is.EqualTo(MathF.PI).Within(1e-5f));
        Assert.That(degrees(MathF.PI), Is.EqualTo(180f).Within(1e-3f));

        var fraction = modf(1.25f, out var integral);
        Assert.That(integral, Is.EqualTo(1f));
        Assert.That(fraction, Is.EqualTo(0.25f));

        // the half of a value that is created from a double is converted to the type it is a member of
        Assert.That(min((Half)1, (Half)2), Is.EqualTo((Half)1));
        Assert.That(sqrt((Half)4), Is.EqualTo((Half)2));
        Assert.That((float)radians((Half)180), Is.EqualTo((float)(Half)MathF.PI).Within(0.01f));
    }

    [Test]
    public void Ieee754()
    {
        Assert.That(sqrt(4f), Is.EqualTo(2f));
        Assert.That(rsqrt(0.25f), Is.EqualTo(2f));
        Assert.That(sqrt(4d), Is.EqualTo(2d));
        Assert.That(log(1d), Is.EqualTo(0d));
        Assert.That(log2(8f), Is.EqualTo(3f).Within(1e-5f));
        Assert.That(log10(1000f), Is.EqualTo(3f).Within(1e-5f));
        Assert.That(log(8f, 2f), Is.EqualTo(3f).Within(1e-5f));
        Assert.That(exp(0d), Is.EqualTo(1d));
        Assert.That(exp2(3f), Is.EqualTo(8f).Within(1e-4f));
        Assert.That(exp10(2f), Is.EqualTo(100f).Within(1e-3f));
        Assert.That(pow(2f, 10f), Is.EqualTo(1024f));
        Assert.That(sin(0f), Is.EqualTo(0f));
        Assert.That(cos(0f), Is.EqualTo(1f));
        Assert.That(tan(0f), Is.EqualTo(0f));
        Assert.That(asin(0f), Is.EqualTo(0f));
        Assert.That(acos(1f), Is.EqualTo(0f));
        Assert.That(atan(0f), Is.EqualTo(0f));
        Assert.That(atan2(0f, 1f), Is.EqualTo(0f));
        Assert.That(sinh(0f), Is.EqualTo(0f));
        Assert.That(cosh(0f), Is.EqualTo(1f));
        Assert.That(tanh(0f), Is.EqualTo(0f));
        Assert.That(asinh(0f), Is.EqualTo(0f));
        Assert.That(acosh(1f), Is.EqualTo(0f));
        Assert.That(atanh(0f), Is.EqualTo(0f));

        var (sine, cosine) = sincos(0f);
        Assert.That(sine, Is.EqualTo(0f));
        Assert.That(cosine, Is.EqualTo(1f));
        sincos(0f, out var outSin, out var outCos);
        Assert.That(outSin, Is.EqualTo(0f));
        Assert.That(outCos, Is.EqualTo(1f));

        Assert.That(is_NaN(float.NaN), Is.True);
        Assert.That(is_NaN(0f), Is.False);
        Assert.That(is_finite(0f), Is.True);
        Assert.That(is_finite(float.NaN), Is.False);
        Assert.That(is_inf(float.PositiveInfinity), Is.True);
        Assert.That(is_pos_inf(float.PositiveInfinity), Is.True);
        Assert.That(is_neg_inf(float.PositiveInfinity), Is.False);
        Assert.That(is_neg_inf(double.NegativeInfinity), Is.True);
    }

    [Test]
    public void Integer()
    {
        Assert.That(is_pow2(8), Is.True);
        Assert.That(is_pow2(0), Is.False);
        Assert.That(is_pow2(-8), Is.False);
        Assert.That(is_pow2(5u), Is.False);
        Assert.That(up2pow2(5u), Is.EqualTo(8u));
        Assert.That(up2pow2(8ul), Is.EqualTo(8ul));
        Assert.That(up2pow2(0u), Is.EqualTo(0u));
    }

    /// <summary>
    /// The select of a value takes a condition instead of a value of its own type, the member that is called on
    /// a value is called on the condition.
    /// </summary>
    [Test]
    public void Select()
    {
        Assert.That(select(true, 1, 2), Is.EqualTo(1));
        Assert.That(select(false, 1, 2), Is.EqualTo(2));
        Assert.That(select(true, 1.5f, 2.5f), Is.EqualTo(1.5f));
        Assert.That(select(false, 1.5, 2.5), Is.EqualTo(2.5));
        Assert.That(select(false, (Half)1, (Half)2), Is.EqualTo((Half)2));
        Assert.That(select(true, 1u, 2u), Is.EqualTo(1u));

        Assert.That(true.select(1, 2), Is.EqualTo(1));
        Assert.That(false.select(1, 2), Is.EqualTo(2));
        Assert.That(false.select(1u, 2u), Is.EqualTo(2u));
        Assert.That(false.select(1.5f, 2.5f), Is.EqualTo(2.5f));
    }

    /// <summary>
    /// The members that are called on a value are the second form of every function of the <c>math</c> class.
    /// </summary>
    [Test]
    public void ValueMembers()
    {
        Assert.That(3.min(5), Is.EqualTo(3));
        Assert.That(3.max(5), Is.EqualTo(5));
        Assert.That(7.clamp(1, 5), Is.EqualTo(5));
        Assert.That((-4).abs(), Is.EqualTo(4));
        Assert.That(3.square(), Is.EqualTo(9));
        Assert.That(3.dot(4), Is.EqualTo(12));
        Assert.That(5.unlerp(0, 10), Is.EqualTo(0));
        Assert.That(3.remap(0, 3, 0, 9), Is.EqualTo(9));
        Assert.That(4f.sqrt(), Is.EqualTo(2f));
        Assert.That(1.25f.frac(), Is.EqualTo(0.25f));
        // the value that the interpolation is called on is the factor
        Assert.That(0.5.lerp(0.0, 10.0), Is.EqualTo(5.0));
        Assert.That(2f.pow(10f), Is.EqualTo(1024f));
        Assert.That(8f.log(2f), Is.EqualTo(3f).Within(1e-5f));
        Assert.That(3f.atan2(1f), Is.EqualTo(MathF.Atan2(3f, 1f)));
        Assert.That(3f.step(2f), Is.EqualTo(1f));
        Assert.That(0.5f.smoothstep(0f, 1f), Is.EqualTo(0.5f));
        Assert.That(8f.is_finite(), Is.True);
        Assert.That(float.NaN.is_NaN(), Is.True);
        Assert.That(5u.up2pow2(), Is.EqualTo(8u));
        Assert.That(8.is_pow2(), Is.True);

        var fraction = 1.25f.modf(out var integral);
        Assert.That(integral, Is.EqualTo(1f));
        Assert.That(fraction, Is.EqualTo(0.25f));

        0f.sincos(out var outSin, out var outCos);
        Assert.That(outSin, Is.EqualTo(0f));
        Assert.That(outCos, Is.EqualTo(1f));
        var (sin, cos) = 0f.sincos();
        Assert.That(sin, Is.EqualTo(0f));
        Assert.That(cos, Is.EqualTo(1f));
    }
}
