<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Coplt.Mathematics</RootNamespace>
        <AssemblyName>Coplt.Mathematics</AssemblyName>
        <Nullable>enable</Nullable>
        <LangVersion>15.0</LangVersion>
        <TargetFramework>net10.0</TargetFramework>
        <NoWarn>CS8981;CS0169;CS1591</NoWarn>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Version>0.19.0</Version>
        <Description>HLSL-style linear algebra math library with full simd support</Description>
        <PackageProjectUrl>https://github.com/coplt/Coplt.Mathematics</PackageProjectUrl>
        <RepositoryUrl>https://github.com/coplt/Coplt.Mathematics</RepositoryUrl>
        <PackageReadmeFile>Readme.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\Readme.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
        <None Include="..\LICENSE.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SourceGenerator\SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>

</Project>